/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-02 01:49:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Date;

public final class notice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String url = request.getServletPath();
session.setAttribute("url",url);
	//2020_01_02 수정부분
	String includeurl = "header.jsp";
	String uss = (String) session.getAttribute("id");
	String log = "로그인";
	if (uss == null)
		uss = "GUEST";
	else {
		log = "로그아웃";
		includeurl = "sign_login.jsp";
	}
	//수정부분 끝
	//2020.01.14 로그인 id 수정
	String yid = (String) session.getAttribute("id");

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"Generator\" content=\"EditPlus®\">\r\n");
      out.write("<meta name=\"Author\" content=\"\">\r\n");
      out.write("<meta name=\"Keywords\" content=\"\">\r\n");
      out.write("<meta name=\"Description\" content=\"\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>league_join_step1</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/boardpop.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/borderRightLeft.css\" media=\"screen\">\r\n");
      out.write("<!-- 광호Q&A -->\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<!--용병리스트 게시판 css파일 수정 2020.01.08-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"yonglist_1_body.css\">\r\n");
      out.write("<!----------------------------바디 스타일------------------------------------>\r\n");
      out.write("\r\n");
      out.write("<!--기본적인 body등의 css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/basicStyle.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/navmid33.css\">\r\n");
      out.write("\r\n");
      out.write("<!--서브메뉴부르는css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style2.css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<!--배너2 자동슬라이드-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.infinitecarousel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!----------------------------서브메뉴마우스오버기능-------------------------->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/subMenuMouseOver.css\">\r\n");
      out.write("<!-- 20200116 용병 버튼 크기 조절 by 문경이형 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/signbutton.css\"> \r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일(따로 빼면 에러)-------------------------->\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#forgot_username_link').tipsy({\r\n");
      out.write("\t\t\tgravity : 'w'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"css/front.css\" media=\"screen, projection\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"js/jquery2.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".signin\").click(function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t$(\"fieldset#signin_menu\").toggle();\r\n");
      out.write("\t\t\t$(\".signin\").toggleClass(\"menu-open\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"fieldset#signin_menu\").mouseup(function() {\r\n");
      out.write("\t\t\treturn false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).mouseup(function(e) {\r\n");
      out.write("\t\t\tif ($(e.target).parent(\"a.signin\").length == 0) {\r\n");
      out.write("\t\t\t\t$(\".signin\").removeClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t$(\"fieldset#signin_menu\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일여기까지------------------------------------>\r\n");
      out.write("<script>\r\n");
      out.write("\t/*스크롤 내리면 메뉴 위치 이동하는 기능------따로빼면 작동xxxxxx*/\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar shrinkHeader = 30;\r\n");
      out.write("\t\tvar shrinkhollow = 465;\r\n");
      out.write("\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\tvar scroll = getCurrentScroll();\r\n");
      out.write("\t\t\tif (scroll >= shrinkHeader) {\r\n");
      out.write("\t\t\t\t$('#navtop').addClass('shrink');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#navtop').removeClass('shrink');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (scroll >= shrinkhollow) {\r\n");
      out.write("\t\t\t\t$('#navtop').addClass('shrinkhollow');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#navtop').removeClass('shrinkhollow');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction getCurrentScroll() {\r\n");
      out.write("\t\t\treturn window.pageYOffset || document.documentElement.scrollTop;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!--2020.01.09Overray css추가 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/qnaOverray.css\">\r\n");
      out.write("<!----------------------------오버레이 화면 띄우는 스크립트------------------------------------>\r\n");
      out.write("<script>\t\t\t\t\t\t\r\n");
      out.write("\tfunction selectOne(index,yid) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\t\r\n");
      out.write("\t\turl:\"./yongSelectOne.jsp\",       \r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tindex:index,\r\n");
      out.write("\t\t\tyid:yid\r\n");
      out.write("\t\t},\t\r\n");
      out.write("\t\tsuccess:whenSuccess2,\r\n");
      out.write("\t\terror:whenError2\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\tfunction whenSuccess2(resdata){\r\n");
      out.write("\t\t\tconsole.log(resdata);\r\n");
      out.write("\t\t\t$(\"#innerpop\").html(resdata);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction whenError2(){\r\n");
      out.write("\t\t\talert(\"리스트에러\");\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("@media screen and (max-width: 1360px)\r\n");
      out.write("#wrapper #container .content > div {\r\n");
      out.write("    padding: 0 20px;\r\n");
      out.write("}\r\n");
      out.write("#wrapper #container .content > div {\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    max-width: 1200px;\r\n");
      out.write("}\r\n");
      out.write(".h_tit {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin-bottom: 45px;\r\n");
      out.write("    padding-bottom: 24px;\r\n");
      out.write("    font-size: 60px;\r\n");
      out.write("    font-family: 'NanumBarunGothicL';\r\n");
      out.write("    line-height: 60px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("h1, h2, h3, h4, h5, h6 {\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write(".h_tit:after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    margin-left: -49px;\r\n");
      out.write("    width: 98px;\r\n");
      out.write("    height: 2px;\r\n");
      out.write("    background: #bfc4cc;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap {\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap.list table {\r\n");
      out.write("    border: 0;\r\n");
      out.write("    border-top: 2px solid #2c3c57;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap table {\r\n");
      out.write("    border: 1px solid #636363;\r\n");
      out.write("    border-top: 0;\r\n");
      out.write("    border-left: 0;\r\n");
      out.write("}\r\n");
      out.write("table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border: 0 none;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    border-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write("table caption {\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 0;\r\n");
      out.write("    line-height: 0px;\r\n");
      out.write("    visibility: hidden;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap.list table thead tr th {\r\n");
      out.write("    padding: 16px 0;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    border-bottom: 1px solid #d5d8dd;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    height: 21px;\r\n");
      out.write("    color: #2c3c57;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    line-height: 21px;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap table thead tr th {\r\n");
      out.write("    padding: 21px 0;\r\n");
      out.write("    height: 22px;\r\n");
      out.write("    background: #f0f1f3;\r\n");
      out.write("    color: #383838;\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("    line-height: 22px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap table th, .table_wrap table td {\r\n");
      out.write("    border-top: 1px solid #636363;\r\n");
      out.write("    border-left: 1px solid #636363;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("table th, table td {\r\n");
      out.write("    border: 0 none;\r\n");
      out.write("}\r\n");
      out.write("table th {\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap.list table tbody tr td {\r\n");
      out.write("    padding: 9px 0;\r\n");
      out.write("    height: 32px;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    border-bottom: 1px solid #d5d8dd;\r\n");
      out.write("    color: #383838;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 32px;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap table tbody tr td {\r\n");
      out.write("    padding: 18px 0;\r\n");
      out.write("    height: 20px;\r\n");
      out.write("    color: #2a2a2a;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    line-height: 28px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    word-break: keep-all;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap table th, .table_wrap table td {\r\n");
      out.write("    border-top: 1px solid #636363;\r\n");
      out.write("    border-left: 1px solid #636363;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("table th, table td {\r\n");
      out.write("    border: 0 none;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap.list table tbody tr td.al_left {\r\n");
      out.write("    padding: 9px 10px;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap table tbody tr td.al_left {\r\n");
      out.write("    padding-left: 20px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write(".al_left {\r\n");
      out.write("    text-align: left !important;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap.list table tbody tr td a.tit {\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    color: #2c3c57;\r\n");
      out.write("    height: 32px;\r\n");
      out.write("    line-height: 32px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("}\r\n");
      out.write("a:visited {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("    color: #000;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".notice_wrap.list table tbody tr td:nth-child(3), .notice_wrap.list table tbody tr td:nth-child(4) {\r\n");
      out.write("    color: #a7a7a7;\r\n");
      out.write("}\r\n");
      out.write(".notice_wrap.list table tbody tr td:nth-child(3), .notice_wrap.list table tbody tr td:nth-child(4) {\r\n");
      out.write("    color: #a7a7a7;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin-top: 42px;\r\n");
      out.write("    \r\n");
      out.write("    line-height: 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    letter-spacing: -10px;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .search {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin-bottom: 42px;\r\n");
      out.write("    \r\n");
      out.write("    line-height: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".select:after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 12px;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    margin-top: -4px;\r\n");
      out.write("    width: 13px;\r\n");
      out.write("    height: 8px;\r\n");
      out.write("    background: url(img/select_arrow.png) no-repeat center center;\r\n");
      out.write("    background-size: 11px auto;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .search .select label {\r\n");
      out.write("    height: 41px;\r\n");
      out.write("    line-height: 41px;\r\n");
      out.write("    letter-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write(".select label {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0px;\r\n");
      out.write("    right: 20px;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 10px;\r\n");
      out.write("    color: #404040;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 38px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .search .select select {\r\n");
      out.write("    height: 41px;\r\n");
      out.write("    line-height: 41px;\r\n");
      out.write("}\r\n");
      out.write(".select select {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    padding: 0 4px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 38px;\r\n");
      out.write("    line-height: 38px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("    filter: alpha(opacity=0);\r\n");
      out.write("}\r\n");
      out.write("select {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    border: 1px solid #999;\r\n");
      out.write("    line-height: 22px;\r\n");
      out.write("    height: 22px;\r\n");
      out.write("    color: #a6a6a6;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .search input {\r\n");
      out.write("    width: 235px;\r\n");
      out.write("    height: 43px;\r\n");
      out.write("    border: 1px solid #d0d0d0;\r\n");
      out.write("    border-left: 0;\r\n");
      out.write("    border-right: 0;\r\n");
      out.write("}\r\n");
      out.write("input[type='text'], input[type='password'] {\r\n");
      out.write("    -webkit-border-radius: 0;\r\n");
      out.write("    -webkit-appearance: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write("input[type='text'], input[type='password'] {\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 3px 9px 3px 9px;\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    color: #383838;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 43px;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("input {\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .search button {\r\n");
      out.write("    width: 69px;\r\n");
      out.write("    height: 43px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    background: #2c3c57 url(img/icon_search.png) no-repeat center center;\r\n");
      out.write("}\r\n");
      out.write("button {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    font-family: 'Nanum Gothic','맑은 고딕','AppleGothic','돋움','Dotum', sans-serif;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    -webkit-transition: all 0.25s ease-out;\r\n");
      out.write("    -moz-transition: all 0.25s ease-out;\r\n");
      out.write("    -ms-transition: all 0.25s ease-out;\r\n");
      out.write("    -o-transition: all 0.25s ease-out;\r\n");
      out.write("    transition: all 0.25s ease-out;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap a.btn_page.prev {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    background: #fff url(img/icn_page_prev.png) no-repeat center center;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap a.btn_page {\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap a {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-left: 8px;\r\n");
      out.write("    width: 79px;\r\n");
      out.write("    height: 41px;\r\n");
      out.write("    border: 1px solid #cecece;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    color: #afafaf;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 41px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    letter-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write("a:visited {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("    color: #000;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".hide {\r\n");
      out.write("    display: block;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 0;\r\n");
      out.write("    text-indent: -9999px;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .page {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin: 0 22px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .page a.on {\r\n");
      out.write("    border: 1px solid #2c3c57;\r\n");
      out.write("    background: #2c3c57;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .page a:first-child {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .page a {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 41px;\r\n");
      out.write("    height: 41px;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap a {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-left: 8px;\r\n");
      out.write("    width: 79px;\r\n");
      out.write("    height: 41px;\r\n");
      out.write("    border: 1px solid #cecece;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    color: #afafaf;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 41px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    letter-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write("a:visited {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("    color: #000;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap a.btn_page.next {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    background: #fff url(img/icn_page_next.png) no-repeat center center;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .search .select {\r\n");
      out.write("    width: 90px;\r\n");
      out.write("    height: 43px;\r\n");
      out.write("    border: 1px solid #d0d0d0;\r\n");
      out.write("    border-right: 0;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("}\r\n");
      out.write(".select {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    border: 1px solid #e0e0e0;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 유즈빈 사용 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, includeurl, out, false);
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div id=\"mainleft\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"leftbanner\">\r\n");
      out.write("\t\t\t<div id=\"banner1\">\r\n");
      out.write("\t\t\t\t<img src=\"img/20191211.jpg\" width=\"100%\" height=\"100%\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"banner3\">\r\n");
      out.write("\t\t\t\t<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25325.265446899888!2d127.02924799651784!3d37.492391917303266!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357ca5bed583f92d%3A0xc93c837d2875ade6!2z7ZKL7IK07J6l!5e0!3m2!1sko!2skr!4v1575961834128!5m2!1sko!2skr\" width=\"100%\" height=\"100%\" frameborder=\"0\" style=\"border: 0;\" allowfullscreen=\"\"></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\t\t<section id=\"mainright\">\r\n");
      out.write("\t\t\t<div id=\"matList\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"cbox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"notice_wrap list\">\r\n");
      out.write("\t\t\t\t<h3 class=\"h_tit\">공지사항</h3>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"table_wrap list\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<caption>공지사항 리스트</caption>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col style=\"width:90px\" class=\"w01\">\r\n");
      out.write("\t\t\t\t\t\t\t<col style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<col style=\"width:155px\" class=\"w02\">\r\n");
      out.write("\t\t\t\t\t\t\t<col style=\"width:85px\" class=\"tb\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">작성일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"tb\">조회</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>19</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=21&amp;page=1\" class=\"tit\">제 2희 손흥민을 꿈꿔라! AIA W&amp;P FC 선수 공개테스트 1기 모집</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2019.06.05</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">987</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>18</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=20&amp;page=1\" class=\"tit\">[2019 플레이컵 풋살 페스티벌]</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2019.04.02</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">6,463</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>17</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=19&amp;page=1\" class=\"tit\">[울산북구점] 불금 풋살 이벤트!</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2019.02.14</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">880</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>16</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=18&amp;page=1\" class=\"tit\">[HM슈퍼메가 이벤트] 제 1회 HMSPORTS배 FIFA 도장깨깃!</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2019.01.22</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">795</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>15</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=17&amp;page=1\" class=\"tit\">2019 HM풋살파크 특급 이벤트! </a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2019.01.07</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">1,035</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>14</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=15&amp;page=1\" class=\"tit\">안산 실내풋살장 HM'락'풋살파크 오픈!!</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.12.07</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">1,427</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>13</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=14&amp;page=1\" class=\"tit\">[챔피언십 성인부]AIA 바이탈리티 2018 H풋살리그 전국 챔피언십 성인부 결과발표!^^</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.12.04</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">709</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>12</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=13&amp;page=1\" class=\"tit\">[챔피언십 초등부]AIA 바이탈리티 2018 H풋살리그 전국 챔피언십 초등부 결과발표!^^</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.12.04</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">581</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>11</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=12&amp;page=1\" class=\"tit\"> [챔피언십 성인부]AIA 바이탈리티 2018 H풋살리그 전국 챔피언십 성인부 조편성 및 대진스케줄 발표! </a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.11.28</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">1,325</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=11&amp;page=1\" class=\"tit\">[챔피언십 초등부]AIA 바이탈리티 2018 H풋살리그 전국 챔피언십 초등부 조편성 및 대진스케줄 발표!</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.11.27</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">1,143</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>9</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=9&amp;page=1\" class=\"tit\">[대전탄방점 성인리그] 폭력 및 비신사적 행위에 따른 양팀 리그 실격패 처리</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.11.23</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">848</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>8</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=8&amp;page=1\" class=\"tit\">[부산가야 성인리그] 부정선수 출전에 따른 해당 경기 실격패 처리 안내</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.11.22</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">886</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>7</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=7&amp;page=1\" class=\"tit\">[서수원점 성인리그] 부정선수 출전에 따른 해당 경기 실격패 처리</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.11.16</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">787</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>6</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=6&amp;page=1\" class=\"tit\">H-LEAGUE 주니어 그룹 부산지역 최종 우승팀 발표</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.11.14</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">657</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>5</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=5&amp;page=1\" class=\"tit\">AIA바이탈리티 H-LEAGUE 이적시장 오픈!</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.11.01</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">1,075</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>4</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=4&amp;page=1\" class=\"tit\">H-LEAGUE 부산가야점 초등부 현장 스케치</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.10.11</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">922</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>3</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=3&amp;page=1\" class=\"tit\">AIA 바이탈리티 H-LEAGUE 서울지역 리그 대망의 START</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.10.02</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">970</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=2&amp;page=1\" class=\"tit\">[HM풋살파크] 홈페이지 서버 정상화 안내</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.09.14</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">792</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"al_left\"><a href=\"comm_notice_view.asp?cno=1&amp;page=1\" class=\"tit\">[HM풋살파크] 홈페이지 개편 안내</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2018.09.12</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"tb\">1,029</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Page -->\r\n");
      out.write("\t\t\t\t<div class=\"pager_wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t\t\t<form name=\"frm_search\" method=\"get\" action=\"?\" onsubmit=\"Fn_Search(); return false;\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"select\" style=\"width:100px\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"select01\">제목</label>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"select01\" name=\"s_kinds\" class=\"select_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"title\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"searchstr\" title=\"\" name=\"searchstr\" value=\"\" style=\"width:200px\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"input\" class=\"btn_search\" onclick=\"Fn_Search(); return false;\"></button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"comm_notice.asp?page=1\" class=\"btn_page prev\"><span class=\"hide\">이전 페이지</span></a><span class=\"page\"><a href=\"comm_notice.asp?page=1\" class=\"on\">1</a></span><a href=\"comm_notice.asp?page=1\" class=\"btn_page next\"><span class=\"hide\">다음 페이지</span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //Page -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
