/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-01 13:38:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.QnaDto;
import dao.QnaDao;
import model.QnaSearchDto;
import java.util.ArrayList;

public final class qna_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.QnaDto");
    _jspx_imports_classes.add("model.QnaSearchDto");
    _jspx_imports_classes.add("dao.QnaDao");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<QnaSearchDto> searchlist = (ArrayList<QnaSearchDto>) request.getAttribute("qnadata");
	String logid = (String) session.getAttribute("id");

	//2020_01_02 수정부분
	String url = request.getServletPath();
	session.setAttribute("url", url);
	String includeurl = "header.jsp";
	String uss = (String) session.getAttribute("id");
	String log = "로그인";
	if (uss == null)
		uss = "GUEST";
	else {
		log = "로그아웃";
		includeurl = "sign_login.jsp";
	}
	//수정부분 끝

      out.write('\r');
      out.write('\n');
      dao.QnaDao dao = null;
      dao = (dao.QnaDao) _jspx_page_context.getAttribute("dao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dao == null){
        dao = new dao.QnaDao();
        _jspx_page_context.setAttribute("dao", dao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"Generator\" content=\"EditPlus®\">\r\n");
      out.write("<meta name=\"Author\" content=\"\">\r\n");
      out.write("<meta name=\"Keywords\" content=\"\">\r\n");
      out.write("<meta name=\"Description\" content=\"\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/borderRightLeft.css\" media=\"screen\">\r\n");
      out.write("<title>qna</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/boardpop.css\">\r\n");
      out.write("<!--기본적인 body등의 css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/basicStyle.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/navmid33.css\">\r\n");
      out.write("<!--Q&A에 펠요한 css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Q&Astyle.css\" media=\"screen\">\r\n");
      out.write("<!-- Q&A에 필요한 script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"Q&Ascript.js\"></script>\r\n");
      out.write("<!-- 광호Q&A -->\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<!--2020.01.03 추가 css 분리-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/logform.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Q&Astyle2.css\" media=\"screen\">\r\n");
      out.write("<!--2020.01.03 추가 javascript.가입기능 분리-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/signjs.js\"></script>\r\n");
      out.write("<!--서브메뉴부르는css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style2.css\" media=\"screen\">\r\n");
      out.write("<!--2020.01.06footer css추가 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("<!--배너2 자동슬라이드-->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.infinitecarousel.js\"></script>\r\n");
      out.write("<!----------------------------서브메뉴마우스오버기능-------------------------->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/subMenuMouseOver.css\">\r\n");
      out.write("<!--2020.01.09Overray css추가 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/qnaOverray.css\">\r\n");
      out.write("\r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일(따로 빼면 에러)-------------------------->\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t  $('#forgot_username_link').tipsy({gravity: 'w'});   \r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"css/front.css\" media=\"screen, projection\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("<script src=\"js/jquery2.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\".signin\").click(function(e) {          \r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t$(\"fieldset#signin_menu\").toggle();\r\n");
      out.write("\t\t\t$(\".signin\").toggleClass(\"menu-open\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"fieldset#signin_menu\").mouseup(function() {\r\n");
      out.write("\t\t\treturn false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).mouseup(function(e) {\r\n");
      out.write("\t\t\tif($(e.target).parent(\"a.signin\").length==0) {\r\n");
      out.write("\t\t\t\t$(\".signin\").removeClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t$(\"fieldset#signin_menu\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!----------------------------alam form 추가 2020.01.06-------------------------->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t$(\".mypage\").click(function(e) {          \r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t$(\"fieldset#mypage_menu\").toggle();\r\n");
      out.write("\t\t\t\t\t$(\".mypage\").toggleClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t});\t\t\r\n");
      out.write("\t\t\t\t$(\"fieldset#mypage_menu\").mouseup(function() {\r\n");
      out.write("\t\t\t\t\treturn false\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(document).mouseup(function(e) {\r\n");
      out.write("\t\t\t\t\tif($(e.target).parent(\"a.mypage\").length!=1) {\r\n");
      out.write("\t\t\t\t\t\t$(\".mypage\").removeClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t\t\t$(\"fieldset#mypage_menu\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일여기까지------------------------------------>\r\n");
      out.write("<script>\r\n");
      out.write(" /*스크롤 내리면 메뉴 위치 이동하는 기능------따로빼면 작동xxxxxx*/\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar shrinkHeader = 30;\r\n");
      out.write("\tvar shrinkhollow = 465;\r\n");
      out.write("\t$(window).scroll(function() {\r\n");
      out.write("\t\tvar scroll = getCurrentScroll();\r\n");
      out.write("\t\t  if ( scroll >= shrinkHeader ) {\r\n");
      out.write("\t\t\t   $('#navtop').addClass('shrink');  \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t$('#navtop').removeClass('shrink');\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t   if(scroll>= shrinkhollow ){\r\n");
      out.write("\t\t\t\t$('#navtop').addClass('shrinkhollow');  \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t$('#navtop').removeClass('shrinkhollow');\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction getCurrentScroll() {\r\n");
      out.write("\t\treturn window.pageYOffset || document.documentElement.scrollTop;\r\n");
      out.write("\t\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<!----------------------------오버레이 화면 띄우는 스크립트------------------------------------>\r\n");
      out.write("<script>\t\t\t\t\t\t\r\n");
      out.write("\tfunction selectOne(index) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\t\r\n");
      out.write("\t\turl:\"./qnaSelectOne.jsp\",       \r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tindex:index\r\n");
      out.write("\t\t},\t\r\n");
      out.write("\t\tsuccess:whenSuccess2,\r\n");
      out.write("\t\terror:whenError2\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\tfunction whenSuccess2(resdata){\r\n");
      out.write("\t\t\t$(\"#innerpop\").html(resdata);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction whenError2(){\r\n");
      out.write("\t\t\talert(\"리스트에러\");\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!----------------------------- 비밀글설정-------------------------------- -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"input:radio[name=q_b_secret]\").click(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif ($(\"input[name=q_b_secret]:checked\").val() == \"sc\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"input:password[name=q_b_secretcode]\").attr(\"disabled\", false);\r\n");
      out.write("\r\n");
      out.write("\t\t\t} else if ($(\"input[name=q_b_secret]:checked\").val() == \"pb\") {\r\n");
      out.write("\t\t\t\t$(\"input:password[name=q_b_secretcode]\").attr(\"disabled\", true);\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("function searchselect(){\r\n");
      out.write("\tvar search = document.getElementById(\"search\");\r\n");
      out.write("\tvar val = search.options[search.selectedIndex].value;  //0은 제목 1은 내용\r\n");
      out.write("\tvar word = document.getElementById(\"sel\").value;\r\n");
      out.write("\talert(val+word);\r\n");
      out.write("\tdocument.location.href=\"qna.do?command=qnasearch&searchword=\"+word+\"&searchsetting=\"+val;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function searchselect1(){\r\n");
      out.write("\tvar search = document.getElementById(\"search\");\r\n");
      out.write("\tvar val = search.options[search.selectedIndex].value;  //0은 제목 1은 내용\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\turl:\"./qna.do?command=qnasearch\",       \r\n");
      out.write("\tdata:{\r\n");
      out.write("\t\r\n");
      out.write("\t\tsearchword:$('#sel').val(),\r\n");
      out.write("\t\tsearchsetting: val\r\n");
      out.write("\t\t\r\n");
      out.write("\t},\t\r\n");
      out.write("\tsuccess:whenSuccess,\r\n");
      out.write("\terror:whenError\r\n");
      out.write("\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tvar confirmid = \"\";\r\n");
      out.write("\tfunction whenSuccess(resdata){\r\n");
      out.write("\talert(resdata);\r\n");
      out.write("\t//document.location.href=\"qna.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction whenError(){\r\n");
      out.write("\talert(\"Error\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#qnaTopTable td div {\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_ban {\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination li a {\r\n");
      out.write("\tposition: unset;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, includeurl, out, false);
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"mainleft\">\r\n");
      out.write("\t\t<div id=\"leftbanner\">\r\n");
      out.write("\t\t\t<div id=\"banner1\">\r\n");
      out.write("\t\t\t\t<img src=\"img/20191211.jpg\" width=\"100%\" height=\"100%\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"banner3\">\r\n");
      out.write("\t\t\t\t<iframe\r\n");
      out.write("\t\t\t\t\tsrc=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25325.265446899888!2d127.02924799651784!3d37.492391917303266!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357ca5bed583f92d%3A0xc93c837d2875ade6!2z7ZKL7IK07J6l!5e0!3m2!1sko!2skr!4v1575961834128!5m2!1sko!2skr\"\r\n");
      out.write("\t\t\t\t\twidth=\"100%\" height=\"100%\" frameborder=\"0\" style=\"border: 0;\"\r\n");
      out.write("\t\t\t\t\tallowfullscreen=\"\"> </iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\t\t<section id=\"mainright\">\r\n");
      out.write("\t\t\t<div id=\"matList\">\r\n");
      out.write("\t\t\t\t<div class=\"sec_ban2\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav_ban\">\r\n");
      out.write("\t\t\t\t\t\t<li><h3\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 30px; margin-top: 5px; font-size: 50px; font-family: 'NanumBarunGothicL'; line-height: 60px; text-align: center;\">고\r\n");
      out.write("\t\t\t\t\t\t\t\t객 센 터</h3></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"cbox1\">\r\n");
      out.write("\t\t\t\t\t<form id=\"qnainsert\" action=\"qnaInsert.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-striped\" id=\"qnaTopTable\">\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"width: 200px; padding-top: 23px;\">제목</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group has-success\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"q_b_title\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"q_b_title\" style=\"width: 670px; margin-top: 7px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"width: 200px; padding-top: 23px;\">작성자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group has-success\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"q_b_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"q_b_name\" maxlength=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 250px; margin-top: 7px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"width: 200px; padding-top: 23px;\">비밀글 설정</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group has-warning\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"height: 45px; text-align: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"inputWarning1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color: #8a6d3b;\"> 글 수정,삭제,비밀글 확인시 사용됩니다. </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"checkbox\" style=\"height: 25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"qSecret2\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"qSecret2\" name=\"q_b_secret\" value=\"pb\">공개\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label> <label for=\"qSecret\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"q_b_secret\" name=\"q_b_secret\" value=\"sc\" checked>비밀글\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t설정\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"q_b_secretcode\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"q_b_secretcode\" maxlength=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 250px; margin-top: 7px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"width: 200px; padding-top: 23px;\">내용</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><textarea id=\"q_b_contents\" name=\"q_b_contents\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" rows=\"7\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"resize: none; width: 670px;\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type =\"hidden\" id=\"id\" name =\"id\" value=\"");
      out.print(logid);
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"qna.jsp\" class=\"btn btn-default\" style=\"float: right; margin-left: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t목록 </a> <input type=\"submit\" value=\"글쓰기\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default pull-right\" style=\"margin-right: 20px;\" /><br>\r\n");
      out.write("\t\t\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"cbox2\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr id=\"tabletitle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thno\"><span> No </span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thtitle\" style=\"text-align: center\"><span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t제목 </span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thname\"><span> 작성자 </span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thdate\"><span> 작성일 </span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thview\"><span> 조회 </span></th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t");

								if(searchlist==null){
													ArrayList<vo.QnaDto> list = dao.selectAll();
													
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int i = 0; i < list.size(); i++) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"thgongji\" style=\"text-align: left;\">");
      out.print(list.get(i).getQ_b_no());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"thtitle\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonClick=\"selectOne(");
      out.print(list.get(i).getQ_b_no());
      out.write("); \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"button\" id=\"listtt\">");
      out.print(list.get(i).getQ_b_title());
      out.write("</a> ");

 									if (list.get(i).getQ_b_secret().equals("sc"))
 										out.print("<img src='img/lock2.png' class='secretimg' style='width: 15px; height: 15px;'>");
 								
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"thname\" name=\"thname\" id=\"thname\">");
      out.print(list.get(i).getQ_b_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"thdate\">");
      out.print(list.get(i).getQ_b_date());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"thview\">");
      out.print(list.get(i).getQ_b_readcount());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							}else if(searchlist!=null){
								
								
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									for (int i = 0; i < searchlist.size(); i++) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"thgongji\" style=\"text-align: left;\">");
      out.print(searchlist.get(i).getQ_b_no());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"thtitle\"><a class=\"button\" id=\"listtt\" onClick=\"selectOne(");
      out.print(searchlist.get(i).getQ_b_no());
      out.write("); \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(searchlist.get(i).getQ_b_title());
      out.write("</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
if (searchlist.get(i).getQ_b_secret().equals("sc"))
								 			out.print("<img src='img/lock2.png' class='secretimg' style='width: 15px; height: 15px;'>");
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"thname\" name=\"thname\" id=\"thname\">");
      out.print(searchlist.get(i).getQ_b_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"thdate\">");
      out.print(searchlist.get(i).getQ_b_date());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"thview\">");
      out.print(searchlist.get(i).getQ_b_readcount());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
							}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"innerHtml\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"innerpop\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" style=\"position: unset;\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" style=\"position: unset;\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" style=\"position: unset;\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" style=\"position: unset;\">4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" style=\"position: unset;\">5</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" style=\"position: unset;\">6</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" style=\"position: unset;\">7</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" style=\"position: unset;\">8</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" style=\"position: unset;\">9</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" style=\"position: unset;\">10</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" style=\"position: unset;\">다음 ></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<select class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 200px; float: left; margin-left: 102px;\">\r\n");
      out.write("\t\t\t\t\t\t<option>전체기간\r\n");
      out.write("\t\t\t\t\t</select> <select class=\"form-control\" name=\"search\" id=\"search\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 200px; float: left; margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">제목\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">내용\r\n");
      out.write("\t\t\t\t\t</select> <input type=\"text\" class=\"form-control\" id=\"sel\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"검색어를 입력하세요\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 300px; float: left; margin-left: 10px;\"> <input\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-default\" type=\"button\" value=\"검 색\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"searchselect()\" style=\"float: left; margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "quickbar.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
