/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-02 05:51:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.BranchDto;
import model.GroundDto;
import java.util.ArrayList;

public final class reservation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.BranchDto");
    _jspx_imports_classes.add("model.GroundDto");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	//2020_01_02 수정부분
	String url = request.getServletPath();
	session.setAttribute("url", url);
	String includeurl = "header.jsp";
	String uss = (String) session.getAttribute("id");
	String log = "로그인";
	if (uss == null)
		uss = "GUEST";
	else {
		log = "로그아웃";
		includeurl = "sign_login.jsp";
	}
	//수정부분 끝

      out.write('\r');
      out.write('\n');

	ArrayList<BranchDto> BranchList = (ArrayList<BranchDto>) request.getAttribute("BranchList");
	ArrayList<GroundDto> GroundList = (ArrayList<GroundDto>) request.getAttribute("GroundList");

      out.write("\r\n");
      out.write("<!-- datepicker -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Roboto:400,500,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<!-- <link rel='stylesheet' type='text/css' href='http://fian.my.id/Waves/static/waves.min.css?v=0.7.4'> -->\r\n");
      out.write("<link rel='stylesheet' type='text/css' href='css/rm-datepicker.css'>\r\n");
      out.write("<!-- ---------- -->\r\n");
      out.write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>대관신청</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta content=\"IE=edge\" http-equiv=\"X-UA-Compatible\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n");
      out.write("<meta content=\"Chrissy Collins\" name=\"author\">\r\n");
      out.write("<meta content=\"A pure vanilla JS calendar by @chrisssycollins\" name=\"description\">\r\n");
      out.write("<link href=\"css/vanillaCalendar.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/classic.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/classic.date.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/classic.time.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/orbit-1.2.3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reservation_body.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/demo-style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style2.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/borderRightLeft.css\" media=\"screen\">\r\n");
      out.write("<link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Roboto:100,300,400'>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/selectstyle.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/form_check.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery-1.5.1.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"reservation_body.css\">\r\n");
      out.write("<!----------------------------바디 스타일------------------------------------>\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.infinitecarousel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--2020.01.03 추가 css 분리-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/logform.css\" media=\"screen\">\r\n");
      out.write("<!--2020.01.03 추가 javascript.가입기능 분리-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/signjs.js\"></script>\r\n");
      out.write("<!--기본적인 body등의 css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/basicStyle.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/navmid33.css\">\r\n");
      out.write("<!-- select box -->\r\n");
      out.write("<script src=\"js/selectindex.js\"></script>\r\n");
      out.write("<!----------------------------서브메뉴마우스오버기능-------------------------->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/subMenuMouseOver.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(window).load(function() {\r\n");
      out.write("\t\t$('#featured').orbit();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t/*스크롤 내리면 메뉴 위치 이동하는 기능------따로빼면 작동xxxxxx*/\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar shrinkHeader = 30;\r\n");
      out.write("\t\tvar shrinkhollow = 465;\r\n");
      out.write("\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\tvar scroll = getCurrentScroll();\r\n");
      out.write("\t\t\tif (scroll >= shrinkHeader) {\r\n");
      out.write("\t\t\t\t$('#navtop').addClass('shrink');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#navtop').removeClass('shrink');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (scroll >= shrinkhollow) {\r\n");
      out.write("\t\t\t\t$('#navtop').addClass('shrinkhollow');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#navtop').removeClass('shrinkhollow');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction getCurrentScroll() {\r\n");
      out.write("\t\t\treturn window.pageYOffset || document.documentElement.scrollTop;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js\"></script>\r\n");
      out.write("<!-- <script src=\"http://fian.my.id/Waves/static/waves.min.js?v=0.7.4\"></script> -->\r\n");
      out.write("<script src=\"js/rm-datepicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar app = angular.module(\"myApp\", [ \"rmDatepicker\" ]);\r\n");
      out.write("\r\n");
      out.write("\t/* Datepicker global configuration */\r\n");
      out.write("\tapp.config([ \"rmDatepickerConfig\", function(rmDatepickerConfig) {\r\n");
      out.write("\t\trmDatepickerConfig.mondayStart = true;\r\n");
      out.write("\t\trmDatepickerConfig.initState = \"month\";\r\n");
      out.write("\t} ]);\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t(function() {\r\n");
      out.write("\t\tvar app = angular.module(\"myApp\");\r\n");
      out.write("\t\tvar MyCtrl = function($scope) {\r\n");
      out.write("\t\t\t/* Datepicker local configuration */\r\n");
      out.write("\t\t\t$scope.rmConfig1 = {\r\n");
      out.write("\t\t\t\tmondayStart : false,\r\n");
      out.write("\t\t\t\tinitState : \"month\", /* decade || year || month */\r\n");
      out.write("\t\t\t\tmaxState : \"decade\",\r\n");
      out.write("\t\t\t\tminState : \"month\",\r\n");
      out.write("\t\t\t\tdecadeSize : 12,\r\n");
      out.write("\t\t\t\tmonthSize : 42, /* \"auto\" || fixed nr. (35 or 42) */\r\n");
      out.write("\t\t\t\tmin : new Date('2000-11-21'),\r\n");
      out.write("\t\t\t\tmax : new Date('2023-11-21'),\r\n");
      out.write("\t\t\t\tformat : \"yyyy-MM-dd\" /* https://docs.angularjs.org/api/ng/filter/date */\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t$scope.oDate1 = new Date();\r\n");
      out.write("\t\t\t$scope.oDate2 = new Date();\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tapp.controller(\"MyCtrl\", [ '$scope', MyCtrl ]);\r\n");
      out.write("\t}());\r\n");
      out.write("\t// Init waves (OPTIONAL) :)\r\n");
      out.write("\t// window.onload = Waves.init();\r\n");
      out.write("</script>\r\n");
      out.write("<SCRIPT type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<style>\r\n");
      out.write(".box {\r\n");
      out.write("\twidth: 450px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- datepicker -->\r\n");
      out.write("<style>\r\n");
      out.write(".container {\r\n");
      out.write("\tmax-width: 320px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("\tline-height: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* input {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("} */\r\n");
      out.write("</style>\r\n");
      out.write("<!-- -------- -->\r\n");
      out.write("<style>\r\n");
      out.write(".inputGroup {\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin: 10px 0;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputGroup label {\r\n");
      out.write("\tpadding: 12px 30px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tcolor: #3C454C;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tz-index: 2;\r\n");
      out.write("\t-webkit-transition: color 200ms ease-in;\r\n");
      out.write("\ttransition: color 200ms ease-in;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tletter-spacing: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputGroup label:before {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 10px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tcontent: '';\r\n");
      out.write("\tbackground-color: #d4332e;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\t-webkit-transform: translate(-50%, -50%) scale3d(1, 1, 1);\r\n");
      out.write("\ttransform: translate(-50%, -50%) scale3d(1, 1, 1);\r\n");
      out.write("\t-webkit-transition: all 300ms cubic-bezier(0.4, 0, 0.2, 1);\r\n");
      out.write("\ttransition: all 300ms cubic-bezier(0.4, 0, 0.2, 1);\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\tz-index: -1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputGroup label:after {\r\n");
      out.write("\twidth: 32px;\r\n");
      out.write("\theight: 32px;\r\n");
      out.write("\tcontent: '';\r\n");
      out.write("\tborder: 2px solid #D1D7DC;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tbackground-image:\r\n");
      out.write("\t\turl(\"data:image/svg+xml,%3Csvg width='32' height='32' viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M5.414 11L4 12.414l5.414 5.414L20.828 6.414 19.414 5l-10 10z' fill='%23fff' fill-rule='nonzero'/%3E%3C/svg%3E \");\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-position: 2px 3px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tz-index: 2;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 30px;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\t-webkit-transform: translateY(-50%);\r\n");
      out.write("\ttransform: translateY(-50%);\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\t-webkit-transition: all 200ms ease-in;\r\n");
      out.write("\ttransition: all 200ms ease-in;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputGroup input:checked ~ label {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputGroup input:checked ~ label:before {\r\n");
      out.write("\t-webkit-transform: translate(-50%, -50%) scale3d(56, 56, 1);\r\n");
      out.write("\ttransform: translate(-50%, -50%) scale3d(56, 56, 1);\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputGroup input:checked ~ label:after {\r\n");
      out.write("\tbackground-color: #003e73;\r\n");
      out.write("\tborder-color: #003e73;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputGroup input {\r\n");
      out.write("\twidth: 32px;\r\n");
      out.write("\theight: 32px;\r\n");
      out.write("\t-webkit-box-ordinal-group: 2;\r\n");
      out.write("\torder: 1;\r\n");
      out.write("\tz-index: 2;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 30px;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\t-webkit-transform: translateY(-50%);\r\n");
      out.write("\ttransform: translateY(-50%);\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tvisibility: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputGroup form {\r\n");
      out.write("\tpadding: 0 16px;\r\n");
      out.write("\tmax-width: 550px;\r\n");
      out.write("\tmargin: 50px auto;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tline-height: 36px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body .inputGroup {\r\n");
      out.write("\tbackground-color: #D1D7DC;\r\n");
      out.write("\tfont-family: 'Fira Sans', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputGroup, .inputGroup::before, .inputGroup::after {\r\n");
      out.write("\tbox-sizing: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputGroup {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("code {\r\n");
      out.write("\tbackground-color: #9AA3AC;\r\n");
      out.write("\tpadding: 0 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ground_name {\r\n");
      out.write("\twidth: 1002px;\r\n");
      out.write("\theight: 47px;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, includeurl, out, false);
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"mainleft\" style=\"height: 1600px;\">\r\n");
      out.write("\t\t<div id=\"leftbanner\">\r\n");
      out.write("\t\t\t<div id=\"banner1\">\r\n");
      out.write("\t\t\t\t<img src=\"img/20191211.jpg\" width=\"100%\" height=\"100%\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"banner3\">\r\n");
      out.write("\t\t\t\t<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25325.265446899888!2d127.02924799651784!3d37.492391917303266!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357ca5bed583f92d%3A0xc93c837d2875ade6!2z7ZKL7IK07J6l!5e0!3m2!1sko!2skr!4v1575961834128!5m2!1sko!2skr\" width=\"100%\" height=\"100%\" frameborder=\"0\" style=\"border: 0;\" allowfullscreen=\"\"></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\t\t<section id=\"mainright\" style=\"margin-top: 60px;\">\r\n");
      out.write("\t\t\t<form name=\"reservation_input\" id=\"materialForm\" class=\"form\" method=\"post\"\r\n");
      out.write("\t\t\taction=\"reservation.do?command=reservation_input\" role=\"form\"\r\n");
      out.write("\t\t\tautocomplete=\"off\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (GroundList != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!------------------------------ datepicker ---------------------------->\r\n");
      out.write("\t\t\t\t<!-- 아랫줄 max-width:달력 가로길이 -->\r\n");
      out.write("\t\t\t\t<div ng-app=\"myApp\" ng-controller=\"MyCtrl\" class=\"container\" style=\"max-width: 1025px; margin-left: -12px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div rm-datepicker ng-model=\"oDate1\" rm-config=\"rmConfig1\" class=\"datepick\"></div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div style=\"font-size: 18px; text-align: left; letter-spacing: 1px;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"hiddendate\" value=\"{{oDate1 | date: 'yyyy-MM-dd'}}\" id=\"hiddendate\">\r\n");
      out.write("\t\t\t\t\t\t날짜선택 : {{oDate1 | date: 'yyyy-MM-dd'}}\r\n");
      out.write("\t\t\t\t\t\t<label id=\"weeklabel\" for=\"weeklabel\"></label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".datepick\").click(function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar date = document.getElementById(\"hiddendate\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar week = ['일','월','화','수','목','금','토' ];\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar pickdate = new Date(date.value);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar dayOfWeek = week[pickdate.getDay()];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#weeklabel\").html(dayOfWeek);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t //groundchange이벤트를 선택할때!\r\n");
      out.write("\t\t\t\t\t\t\t\t\t var gname = $(\"#ground_name option:selected\").val();\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(gname==\"구장\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#ground_name\").val(\"A구장\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar gname = $(\"#ground_name option:selected\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tselectAjax(gname);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar checkboxline = document.getElementById(\"checkboxline\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcheckboxline.style.removeProperty(\"display\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- ---------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction selectAjax(value) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\turl : \"./groundselect.do?command=selectground\",\r\n");
      out.write("\t\t\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\tground_name : value\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : whenSuccesstime,\r\n");
      out.write("\t\t\t\t\t\t\terror : whenError\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tfunction whenSuccesstime(resdata) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar x = document.getElementById(\"selectajax\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar clickground_no = resdata[0].clickground_no\r\n");
      out.write("\t\t\t\t\t\tvar weekAM_charge = resdata[0].weekAM_charge\r\n");
      out.write("\t\t\t\t\t\tvar weekPM_charge = resdata[0].weekPM_charge\r\n");
      out.write("\t\t\t\t\t\tvar weekendAM_charge = resdata[0].weekendAM_charge\r\n");
      out.write("\t\t\t\t\t\tvar weekendPM_charge = resdata[0].weekendPM_charge\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar weekweek = $(\"label[for='weeklabel']\").text();\r\n");
      out.write("\t\t\t\t\t\tif (weekweek == \"토\") {\r\n");
      out.write("\t\t\t\t\t\t\t$(\".weekAM_charge\").html(weekendAM_charge);\r\n");
      out.write("\t\t\t\t\t\t\t$('.weekAM_charge').val(weekendAM_charge);\r\n");
      out.write("\t\t\t\t\t\t\t$(\".weekPM_charge\").html(weekendPM_charge);\r\n");
      out.write("\t\t\t\t\t\t\t$('.weekPM_charge').val(weekendPM_charge);\r\n");
      out.write("\t\t\t\t\t\t} else if (weekweek == \"일\") {\r\n");
      out.write("\t\t\t\t\t\t\t$(\".weekAM_charge\").html(weekendAM_charge);\r\n");
      out.write("\t\t\t\t\t\t\t$('.weekAM_charge').val(weekendAM_charge);\r\n");
      out.write("\t\t\t\t\t\t\t$(\".weekPM_charge\").html(weekendPM_charge);\r\n");
      out.write("\t\t\t\t\t\t\t$('.weekPM_charge').val(weekendPM_charge);\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$(\".weekAM_charge\").html(weekAM_charge);\r\n");
      out.write("\t\t\t\t\t\t\t$('.weekAM_charge').val(weekAM_charge);\r\n");
      out.write("\t\t\t\t\t\t\t$(\".weekPM_charge\").html(weekPM_charge);\r\n");
      out.write("\t\t\t\t\t\t\t$('.weekPM_charge').val(weekPM_charge);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar selectvalue = $(\".ground_name\").val();\r\n");
      out.write("\t\t\t\t\t\t//ground_name_id hidden 담기\r\n");
      out.write("\t\t\t\t\t\t$('#ground_name_id').val(selectvalue);\r\n");
      out.write("\t\t\t\t\t\t//res_date hidden 담기\r\n");
      out.write("\t\t\t\t\t\tvar resdate = $(\"#hiddendate\").val();\r\n");
      out.write("\t\t\t\t\t\t$('#res_date_id').val(resdate);\r\n");
      out.write("\t\t\t\t\t\t///ground_no hidden 담기\r\n");
      out.write("\t\t\t\t\t\t$('#ground_no_id').val(clickground_no);\r\n");
      out.write("\t\t\t\t\t\tconsole.log(clickground_no);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tfunction whenError() {\r\n");
      out.write("\t\t\t\t\t\talert(\"Error\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t//셀렉트박스 change 이벤트\r\n");
      out.write("\t\t\t\t\tfunction groundchange(mege) {\r\n");
      out.write("\t\t\t\t\t\tvar groundselect = this.value;\r\n");
      out.write("\t\t\t\t\t\tvar selectvalue = $(\".ground_name\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar weekweek = $(\"label[for='weeklabel']\").text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t//구장선택에따라 스타일부여(display 보이게/안보이게)\r\n");
      out.write("\t\t\t\t\t\tvar checkboxline = document.getElementById(\"checkboxline\");\r\n");
      out.write("\t\t\t\t\t\tif (selectvalue == \"구장\") {\r\n");
      out.write("\t\t\t\t\t\t\tcheckboxline.style.setProperty('display', 'none');\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tselectAjax(mege);\r\n");
      out.write("\t\t\t\t\t\t\tcheckboxline.style.removeProperty(\"display\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<select name=\"ground_name\" class=\"ground_name\" id=\"ground_name\" onChange=\"groundchange(this.value)\">\r\n");
      out.write("\t\t\t\t\t<option value=\"구장\">구장</option>\r\n");
      out.write("\t\t\t\t\t");

						for (int i = 0; i < GroundList.size(); i++) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(GroundList.get(i).getGround_name());
      out.write('"');
      out.write('>');
      out.print(GroundList.get(i).getGround_name());
      out.write("(크기:");
      out.print(GroundList.get(i).getGround_size());
      out.write(")\r\n");
      out.write("\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"cont_heg_50\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"text-align: left; font-size: 17px; margin-top: 36px;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- --------------------------------------------------------------------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t<!-- Ajax 리턴받는곳 -->\r\n");
      out.write("\t\t\t\t<div id=\"selectajax\" style=\"color: red; font-size: 12px;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div name=\"checkboxline\" id=\"checkboxline\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<div class=\"inputGroup\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"option1\" class=\"checkboxsquere\" name=\"check_time\" value=\"08:00 AM ~ 10:00 AM\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"option1\"> 08:00 AM ~ 10:00 AM\r\n");
      out.write("\t\t\t\t\t\t\t<div name=\"click_charge\" class=\"weekAM_charge\" id=\"weekAM_charge\" value=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"inputGroup\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"option2\" class=\"checkboxsquere\" name=\"check_time\" value=\"10:00 AM ~ 12:00 PM\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"option2\"> 10:00 AM ~ 12:00 PM\r\n");
      out.write("\t\t\t\t\t\t\t<div name=\"click_charge\" class=\"weekAM_charge\" id=\"weekAM_charge\" value=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"inputGroup\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"option3\" class=\"checkboxsquere\" name=\"check_time\" value=\"12:00 PM ~ 02:00 PM\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"option3\"> 12:00 PM ~ 02:00 PM\r\n");
      out.write("\t\t\t\t\t\t\t<div name=\"click_charge\" class=\"weekAM_charge\" id=\"weekAM_charge\" value=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"inputGroup\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"option4\" class=\"checkboxsquere\" name=\"check_time\" value=\"02:00 PM ~ 04:00 PM\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"option4\"> 02:00 PM ~ 04:00 PM\r\n");
      out.write("\t\t\t\t\t\t\t<div name=\"click_charge\" class=\"weekAM_charge\" id=\"weekAM_charge\" value=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"inputGroup\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"option5\" class=\"checkboxsquere\" name=\"check_time\" value=\"04:00 PM ~ 06:00 PM\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"option5\"> 04:00 PM ~ 06:00 PM\r\n");
      out.write("\t\t\t\t\t\t\t<div name=\"click_charge\" class=\"weekAM_charge\" id=\"weekAM_charge\" value=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"inputGroup\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"option6\" class=\"checkboxsquere\" name=\"check_time\" value=\"06:00 PM ~ 08:00 PM\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"option6\"> 06:00 PM ~ 08:00 PM\r\n");
      out.write("\t\t\t\t\t\t\t<div name=\"click_charge\" class=\"weekPM_charge\" id=\"weekPM_charge\" value=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"inputGroup\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"option7\" class=\"checkboxsquere\" name=\"check_time\" value=\"08:00 PM ~ 10:00 PM\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"option7\"> 08:00 PM ~ 10:00 PM\r\n");
      out.write("\t\t\t\t\t\t\t<div name=\"click_charge\" class=\"weekPM_charge\" id=\"weekPM_charge\" value=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- --------------------------------------------------------------------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t//체크박스 선택 이벤트 ->합계Ajax\r\n");
      out.write("\t\t\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t\t\t$(\".checkboxsquere\").change(function(e) {\r\n");
      out.write("\t\t\t\t\t\t\tif($(\"input:radio[name='check_time']\").is(\":checked\") == true){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar checkclick = this.value;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar chargename =  $('#'+$(this).attr(\"id\") +' + label div[name=\"click_charge\"]').val();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#totalcharge\").html(checkclick+'  '+chargename+' 원');\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#res_time_id').val(checkclick);\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#res_pay_id').val(chargename);\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t}else if($(\"input:checkbox[name='check_time']\").is(\":checked\") == false)\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#totalcharge\").html(' ');\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<div style=\"text-align: right;font-size: 20px;height: 10px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"totalcharge\" style=\"font-size: 16px;float:right;width: 260px;height: 100%;margin-top: 2px;color:#8e8e8e;\">0 원</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"font-size: 18px;float:right;width: 200px;height: 100%;color:#8e8e8e;\">합계</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t<!-- reservation_tb에 넘기기위해 hidden에 담음 -->\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"branch_no\" value=\"");
      out.print(BranchList.get(0).getBranch_no());
      out.write("\" >\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"ground_no\" id=\"ground_no_id\"  value=\"\" >\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"id\" value=\"");
      out.print(uss);
      out.write("\" >\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"res_date\" id=\"res_date_id\" value=\"\" >\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"res_time\" id=\"res_time_id\" value=\"\" >\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"payment_charge\" id=\"res_pay_id\" value=\"\" >\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"branch_name\" id=\"branch_name_id\" value=\"");
      out.print(BranchList.get(0).getBranch_name());
      out.write("\" >\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"ground_name_id\" id=\"ground_name_id\" value=\"\" >\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- <input type=\"text\" name=\"res_no\" id=\"res_no_id\" value=\"\" > -->\r\n");
      out.write("\t\t\t\t<!-- --------------------------------- -->\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<hr style=\"margin-top: 13px;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input type=\"submit\" class=\"depthButton\" style=\"height: 45px; width: 114px; text-align: center;\r\n");
      out.write("\t\t\tfont-size: 17px; padding-top: 6px; letter-spacing: 13px; float: right;\" value=\"결제\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
