/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-02 05:41:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sign_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	//2020_01_02 수정부분
	String url = request.getServletPath();
	session.setAttribute("url", url);
	String includeurl = "header.jsp";
	String uss = (String) session.getAttribute("id");
	String log = "로그인";
	if (uss == null)
		uss = "GUEST";
	else {
		log = "로그아웃";
		includeurl = "sign_login.jsp";
	}
	//수정부분 끝

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인된 상태로 회원가입페이지 가는것 막기 -->\r\n");

	String strReferer = request.getHeader("referer");

	if (strReferer == null) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\talert(\"정상적인 경로를 통해 다시 접근해 주십시오.\");\r\n");
      out.write("\tdocument.location.href = \"qna.jsp\";\r\n");
      out.write("</script>\r\n");

	return;
	}

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"Generator\" content=\"EditPlus®\">\r\n");
      out.write("<meta name=\"Author\" content=\"\">\r\n");
      out.write("<meta name=\"Keywords\" content=\"\">\r\n");
      out.write("<meta name=\"Description\" content=\"\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/datepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common.js\"></script>\r\n");
      out.write("<!-- form_check.js 없음 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/common/form_check.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css\\join.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/classic.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/classic.date.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/signbutton.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/signformrelocation.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/classic.time.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style2.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/materialFormStyles.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/borderRightLeft.css\" media=\"screen\">\r\n");
      out.write("<script src=\"js/materialForm.js\"></script>\r\n");
      out.write("<!--기본적인 body등의 css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/basicStyle.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/navmid33.css\">\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.infinitecarousel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--2020.01.03 추가 css 분리-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/logform.css\" media=\"screen\">\r\n");
      out.write("<!--2020.01.03 추가 javascript.가입기능 분리-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/signjs.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!----------------------------alam form 추가 2020.01.06-------------------------->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\".mypage\").click(function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t$(\"fieldset#mypage_menu\").toggle();\r\n");
      out.write("\t\t\t$(\".mypage\").toggleClass(\"menu-open\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"fieldset#mypage_menu\").mouseup(function() {\r\n");
      out.write("\t\t\treturn false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).mouseup(function(e) {\r\n");
      out.write("\t\t\tif ($(e.target).parent(\"a.mypage\").length != 0) {\r\n");
      out.write("\t\t\t\t$(\".mypage\").removeClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t$(\"fieldset#mypage_menu\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일여기까지------------------------------------>\r\n");
      out.write("<!----------------------------서브메뉴마우스오버기능-------------------------->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/subMenuMouseOver.css\">\r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일(따로 빼면 에러)-------------------------->\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#forgot_username_link').tipsy({\r\n");
      out.write("\t\t\tgravity : 'w'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"css/front.css\" media=\"screen, projection\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("<script src=\"js/jquery2.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".signin\").click(function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t$(\"fieldset#signin_menu\").toggle();\r\n");
      out.write("\t\t\t$(\".signin\").toggleClass(\"menu-open\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"fieldset#signin_menu\").mouseup(function() {\r\n");
      out.write("\t\t\treturn false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).mouseup(function(e) {\r\n");
      out.write("\t\t\tif ($(e.target).parent(\"a.signin\").length == 0) {\r\n");
      out.write("\t\t\t\t$(\".signin\").removeClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t$(\"fieldset#signin_menu\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일여기까지------------------------------------>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar shrinkHeader = 30;\r\n");
      out.write("\t\tvar shrinkhollow = 465;\r\n");
      out.write("\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\tvar scroll = getCurrentScroll();\r\n");
      out.write("\t\t\tif (scroll >= shrinkHeader) {\r\n");
      out.write("\t\t\t\t$('#navtop').addClass('shrink');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#navtop').removeClass('shrink');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (scroll >= shrinkhollow) {\r\n");
      out.write("\t\t\t\t$('#navtop').addClass('shrinkhollow');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#navtop').removeClass('shrinkhollow');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction getCurrentScroll() {\r\n");
      out.write("\t\t\treturn window.pageYOffset || document.documentElement.scrollTop;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- -----------------다음 주소 api ----------------------------------------->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<!-- ------------------------------------------------------------------------- -->\r\n");
      out.write("<!-- -------------------------ID 중복확인에 대한 ajax--------------------------------- -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#id\").blur(function() {\r\n");
      out.write("\t\t\tvar idReg = /^[a-zA-z]+[a-zA-z0-9]{5,13}$/g;\r\n");
      out.write("\t\t\tif (idReg.test(join.id.value))\r\n");
      out.write("\t\t\t\tcallAjax();\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t$(\"#ajaxReturn\").html(\"6~12자 사이의 영문 대소문자와 숫자만 사용가능합니다\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tvar n = document.getElementById(\"nameReturn\");\r\n");
      out.write("\t\t$(\"#name\").blur(function() {\r\n");
      out.write("\t\t\tif (join.name.value.length != 0)\r\n");
      out.write("\t\t\t\t$(\"#nameReturn\").html(\"\");\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t$(\"#nameReturn\").html(\"이름을 입력해주세요.\");\r\n");
      out.write("\t\t\t\tn.style.color = \"red\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#tel2\").blur(function() {\r\n");
      out.write("\t\t\tif (join.hp2.value.length != 0)\r\n");
      out.write("\t\t\t\t$(\"#hpReturn\").html(\"\");\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t$(\"#hpReturn\").html(\"휴대폰번호를 입력하세요.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#tel3\").blur(function() {\r\n");
      out.write("\t\t\tif (join.hp3.value.length != 0)\r\n");
      out.write("\t\t\t\t$(\"#hpReturn\").html(\"\");\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t$(\"#hpReturn\").html(\"휴대폰번호를 입력하세요.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#email1\").blur(function() {\r\n");
      out.write("\t\t\tif (join.em1.value.length != 0)\r\n");
      out.write("\t\t\t\t$(\"#emReturn\").html(\"\");\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t$(\"#emReturn\").html(\"이메일을 입력하세요.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction callAjax() {\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\turl : \"./idcheck.do?command=idcheck\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tid : $('#id').val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : whenSuccess,\r\n");
      out.write("\t\t\terror : whenError\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tvar confirmid = \"\";\r\n");
      out.write("\tfunction whenSuccess(resdata) {\r\n");
      out.write("\t\tvar x = document.getElementById(\"ajaxReturn\");\r\n");
      out.write("\t\t$(\"#ajaxReturn\").html(resdata);\r\n");
      out.write("\r\n");
      out.write("\t\tif (resdata.includes(\"이미 사용중인 ID입니다\")) {\r\n");
      out.write("\t\t\tdocument.join.hidden.value = \"0\";\r\n");
      out.write("\t\t\tx.style.color = \"red\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\tdocument.join.hidden.value = \"1\";\r\n");
      out.write("\t\t\tx.style.color = \"blue\";\r\n");
      out.write("\t\t\tconfirmid = join.id.value;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction whenError() {\r\n");
      out.write("\t\talert(\"Error\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 비밀번호 체크 ajax -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction callAjax2() {\r\n");
      out.write("\t\tif (join.pw.value != join.pwch.value) {\r\n");
      out.write("\t\t\t$(\"#pwReturn\").html(\"비밀번호가 일치하지 않습니다\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\"#pwReturn\").html(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, includeurl, out, false);
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div id=\"mainleft\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"leftbanner\">\r\n");
      out.write("\t\t\t<div id=\"banner1\">\r\n");
      out.write("\t\t\t\t<img src=\"img/20191211.jpg\" width=\"100%\" height=\"100%\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"banner3\">\r\n");
      out.write("\t\t\t\t<iframe\r\n");
      out.write("\t\t\t\t\tsrc=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25325.265446899888!2d147.02924799651784!3d37.492391917303266!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357ca5bed583f92d%3A0xc93c837d2875ade6!2z7ZKL7IK07J6l!5e0!3m2!1sko!2skr!4v1575961834128!5m2!1sko!2skr\"\r\n");
      out.write("\t\t\t\t\twidth=\"100%\" height=\"100%\" frameborder=\"0\" style=\"border: 0;\"\r\n");
      out.write("\t\t\t\t\tallowfullscreen=\"\"></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"mainright\">\r\n");
      out.write("\t\t\t<div id=\"matList\">\r\n");
      out.write("\t\t\t\t<div class=\"container\" id=\"formOutterWrapper\">\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t<h2 id=\"sign_title\">JOIN US</h2>\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t<div class=\"container\" id=\"formInnerWrapper\">\r\n");
      out.write("\t\t\t\t\t\t<form name=\"join\" id=\"materialForm\" class=\"form\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\t\taction=\"input.do?command=signinput\" role=\"form\"\r\n");
      out.write("\t\t\t\t\t\t\tautocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"id\">아이디<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"//img.echosting.cafe24.com/skin/base/common/ico_required.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"필수\"></label> <input type=\"text\" class=\"formInput\" id=\"id\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"id\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"ajaxReturn\" style=\"color: red; font-size: 12px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"name\">이름<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"//img.echosting.cafe24.com/skin/base/common/ico_required.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"필수\"></label> <input type=\"text\" class=\"formInput\" id=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"nameReturn\" style=\"color: red; font-size: 12px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"pw\">비밀번호<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"//img.echosting.cafe24.com/skin/base/common/ico_required.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"필수\"></label> <input type=\"password\" class=\"formInput\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"pw\" name=\"pw\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"pwch\">비밀번호재확인<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"//img.echosting.cafe24.com/skin/base/common/ico_required.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"필수\"></label> <input type=\"password\" class=\"formInput\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"pwch\" name=\"pwch\" onBlur=\"callAjax2()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"pwReturn\" style=\"color: red; font-size: 12px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2 labels\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\"> 휴대폰번호<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"//img.echosting.cafe24.com/skin/base/common/ico_required.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"필수\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"margin-left: -10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"formInput\" id=\"tel1\" name=\"tel1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"010\">010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"016\">016</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"017\">017</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"018\">018</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"019\">019</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"hpReturn\" style=\"color: red; font-size: 12px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"float: left;\">-</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"tel2\"></label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"formInput\" id=\"tel2\" name=\"tel2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"float: left;\">-</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"tel3\"></label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"formInput\" id=\"tel3\" name=\"tel3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"email1\">이메일<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"//img.echosting.cafe24.com/skin/base/common/ico_required.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"필수\"></label> <input type=\"text\" class=\"formInput\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"email1\" name=\"email1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"emReturn\" style=\"color: red; font-size: 12px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"formInput\" id=\"email2\" name=\"email2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"mail\" class=formInput\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonChange=mailaddr(join.mail) style=\"width: 163px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">직접입력</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\">성별</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6 radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label2> <input type=\"radio\" name=\"gender\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"female\" checked>여성 </label2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label2> <input type=\"radio\" name=\"gender\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"male\">남성 </label2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 14px; letter-spacing: 4px; font-weight: 400; width: 182px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\">주소<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"//img.echosting.cafe24.com/skin/base/common/ico_required.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"필수\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"address_code\"></label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" id=\"sample6_postcode\" class=\"formInput\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"address_code\" name=\"address_code\" placeholder=\"우편번호\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treadonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"우편번호 찾기\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"sample6_execDaumPostcode()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-5\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"width: 192px; margin-left: -8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"address_basic\"></label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"formInput\" id=\"sample6_address\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"address_basic\" placeholder=\"주소\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\" style=\"width: 395px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"address_detail\"></label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"formInput\" id=\"sample6_detailAddress\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"address_detail\" placeholder=\"상세주소\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\">생년월일</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-1\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"margin-top: 8px; margin-left: -16px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"birth_year\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1920\">1920</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1921\">1921</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1922\">1922</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1923\">1923</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1924\">1924</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1925\">1925</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1926\">1926</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1927\">1927</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1928\">1928</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1929\">1929</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1930\">1930</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1931\">1931</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1932\">1932</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1933\">1933</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1934\">1934</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1935\">1935</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1936\">1936</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1937\">1937</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1938\">1938</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1939\">1939</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1940\">1940</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1941\">1941</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1942\">1942</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1943\">1943</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1944\">1944</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1945\">1945</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1946\">1946</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1947\">1947</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1948\">1948</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1949\">1949</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1950\">1950</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1951\">1951</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1952\">1952</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1953\">1953</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1954\">1954</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1955\">1955</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1956\">1956</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1957\">1957</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1958\">1958</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1959\">1959</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1960\">1960</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1961\">1961</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1962\">1962</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1963\">1963</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1964\">1964</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1965\">1965</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1966\">1966</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1967\">1967</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1968\">1968</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1969\">1969</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1970\">1970</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1971\">1971</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1972\">1972</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1973\">1973</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1974\">1974</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1975\">1975</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1976\">1976</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1977\">1977</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1978\">1978</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1979\">1979</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1980\">1980</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1981\">1981</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1982\">1982</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1983\">1983</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1984\">1984</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1985\">1985</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1986\">1986</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1987\">1987</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1988\">1988</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1989\">1989</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1990\">1990</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1991\">1991</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1992\">1992</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1993\">1993</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1994\">1994</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1995\">1995</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1996\">1996</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1997\">1997</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1998\">1998</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1999\">1999</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">2000</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2001\">2001</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2002\">2002</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2003\">2003</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2004\">2004</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2005\">2005</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2006\">2006</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2007\">2007</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2008\">2008</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2009\">2009</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2010\">2010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2011\">2011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2012\">2012</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2013\">2013</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2014\">2014</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2015\">2015</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2016\">2016</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2017\">2017</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2018\">2018</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2019\">2019</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2020\">2020</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> <select name=\"birth_month\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"01\">01</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"02\">02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"03\">03</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"04\">04</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"05\">05</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"06\">06</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"07\">07</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"08\">08</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"09\">09</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> <select name=\"birth_day\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"01\">01</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"02\">02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"03\">03</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"04\">04</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"05\">05</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"06\">06</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"07\">07</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"08\">08</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"09\">09</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"13\">13</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"14\">14</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"15\">15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"16\">16</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"17\">17</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"18\">18</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"19\">19</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"20\">20</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"21\">21</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"22\">22</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"23\">23</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"24\">24</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"25\">25</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"26\">26</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"27\">27</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"28\">28</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"29\">29</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"30\">30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"31\">31</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\">사진</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"font-size: 14px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\">실력</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-3\" style=\"margin-left: 82px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"level\" class=formInput>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"5\">상</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"4\">중상</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"3\">중</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">중하</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">하</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"font-size: 14px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 14px; letter-spacing: 4px; font-weight: 400;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\">선호포지션</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-8 checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"checkboxmargin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label2> <input type=\"checkbox\" name=position\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"FW\"> FW </label2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label2> <input type=\"checkbox\" name=position\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"MF\"> MF </label2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label2> <input type=\"checkbox\" name=position\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"DF\"> DF </label2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label2> <input type=\"checkbox\" name=position\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"GK\"> GK </label2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\">비밀번호확인질문</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"second_pw\" size=\"1\" class=formInput\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 340px; height: 30px; margin-left: -15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q01\">기억에 남는 추억의 장소는?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q02\">자신의 인생 좌우명은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q03\">자신의 보물 제1호는?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q04\">가장 기억에 남는 선생님 성함은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q05\">타인이 모르는 자신만의 신체비밀이 있다면?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q06\">받았던 선물 중 기억에 남는 독특한 선물은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q07\">유년시절 가장 생각나는 친구 이름은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q08\">인상 깊게 본 축구경기는?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q09\">신었던 축구화 중에서 제일좋은 축구화는?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q10\">자신이 제일 좋아하는 축구팀은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q11\">공개하지 않는 어릴 적 별명이 있다면?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q12\">초등학교 때 기억에 남는 짝꿍 이름은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q13\">다시 태어나면 되고 싶은 축구선수는?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Q14\">제일 좋아하는 축구선수의 이름은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-8\" style=\"width: 785px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"second_pwc\">비밀번호확인답변</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"formInput\" id=\"second_pwc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"second_pwc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\" style=\"height: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\"> 환불계좌정보<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"//img.echosting.cafe24.com/skin/base/common/ico_required.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"필수\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"margin-top: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"bank_code\" size=\"1\" class=formInput\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 130px; height: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"001\">한국은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"002\">산업은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"003\">기업은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"004\">국민은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"005\">외환은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"007\">수협중앙회</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"008\">농협중앙회</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"011\">농.축협</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"020\">우리은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"023\">SC제일은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"027\">한국씨티은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"045\">새마을금고</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"048\">신협중앙회</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"071\">우체국</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"081\">하나은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"088\">신한은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-3\" style=\"margin-left: -9px; width: 375px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"account_code\">계좌번호</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"formInput\" id=\"account_code\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"account_code\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 16px; font-weight: 400; width: 20px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"width: 203px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"account_holder\">예금주</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"formInput\" id=\"account_holder\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"account_holder\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"margin-left: 90px; margin-bottom: 90px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"가입\" class=\"signbutton signbutton5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonClick=\"joinsubmit()\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"취소\" class=\"signbutton signbuttoncancel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonClick=\"script: location.href='sign.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"hidden\" value=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script src=\"https://code.jquery.com/jquery-2.2.3.min.js\"\r\n");
      out.write("\t\t\t\t\tintegrity=\"sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=\"\r\n");
      out.write("\t\t\t\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t\t\t<script src=\"js/materialForm.js\"></script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
