/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-02 05:42:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sign_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	//2020_01_02 수정부분
	String uss = (String) session.getAttribute("id");
	String log = "로그인";
	if (uss == null)
		uss = "GUEST";
	else
		log = "로그아웃";
	//수정부분 끝
	String headerurl = (String) request.getAttribute("javax.servlet.include.request_uri");
	session.setAttribute("headerurl", headerurl);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!----------------------------alam form 추가 2020.01.06-------------------------->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t$(\".mypage\").click(function(e) {          \r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t$(\"fieldset#mypage_menu\").toggle();\r\n");
      out.write("\t\t\t\t\t$(\".mypage\").toggleClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t});\t\t\r\n");
      out.write("\t\t\t\t$(\"fieldset#mypage_menu\").mouseup(function() {\r\n");
      out.write("\t\t\t\t\treturn false\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(document).mouseup(function(e) {\r\n");
      out.write("\t\t\t\t\tif($(e.target).parent(\"a.mypage\").length!=1) {\r\n");
      out.write("\t\t\t\t\t\t$(\".mypage\").removeClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t\t\t$(\"fieldset#mypage_menu\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("<!--마이페이지 접근 위한 css 파일 추가 2020.01.15-->\r\n");
      out.write("<link href=\"css/frontlogin.css\" media=\"screen, projection\" rel=\"stylesheet\" type=\"text/css\">  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "quickbar.jsp", out, false);
      out.write("\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\r\n");
      out.write("\t\t<video id=\"video01\" autoplay=\"\" playsinline=\"\" muted=\"\" loop=\"\" height=\"460\" width=\"100%\" title=\"video element\">\r\n");
      out.write("\t\t\t<source src=\"img/video element.mp4\" type=\"video/mp4\">\r\n");
      out.write("\t\t</video>\r\n");
      out.write("\t\t<div id=\"navtop\">\r\n");
      out.write("\t\t\t<div id=\"navtop_logo\">\r\n");
      out.write("\t\t\t\t<a href=\"index.do?command=index\"><img src=\"img/logo2.png\" width=\"95px\" height=\"120px\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"navtop_menu\">\r\n");
      out.write("\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"borderRightLeft\"><a href=\"branchlist.do?command=branchlistview\">대관</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"branchlist.do?command=branchlistview\">시설검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"reservation.jsp\">대관신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"branchdetail.jsp\">시설소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"borderRightLeft\"><a href=\"yonglist_1.jsp\">매치/용병</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"match_apply.jsp\">매치신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"yonglist_1.jsp\">용병등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"teamlist.do\">팀원모집</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"borderRightLeft\"><a href=\"league.jsp\">리그</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"borderRightLeft\"><a href=\"galList.bo\">팀커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"galList.bo\">팀갤러리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">팀게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"teamlist.do?command=teamlist\">팀관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">팀가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"borderRightLeft\"><a href=\"qna.jsp\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul style=\"width: 210px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"notice.jsp\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"branch.jsp\">지점등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"groundlistview2.do?command=groundlistview2\">구장등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"navtop_login\">\r\n");
      out.write("\t\t\t\t<!--회원상태 창-->\r\n");
      out.write("\t\t\t\t<div id=\"container\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"topnav\" class=\"topnav\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"logout.jsp\"> <span>");
      out.print(log);
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<a href=\"login\" class=\"signin\" style=\"float: left; line-height: 25px;\"><u style=\"font-size: 17px; font-weight: 300;\">");
      out.print(uss);
      out.write("</u> ∨</a>\r\n");
      out.write("\t\t\t\t<fieldset id=\"signin_menu\">\r\n");
      out.write("\t\t\t\t\t<form name=\"login\" method=\"post\" id=\"signin\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p class=\"forgot\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"Mypage.jsp\" id=\"signin\">My Page</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"forgot\">\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"booking\" href=\"\">예약조회 </a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"forgot\">\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"board\" href=\"\">환불계좌등록 </a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"alampage\" class=\"mypage\" style=\"float: left; line-height: 25px;\"><img src=\"img/alam.png\" style=\"width: 30px; height: 30px; margin-left: 10px;\" /></a>\r\n");
      out.write("\t\t\t\t<fieldset id=\"mypage_menu\">\r\n");
      out.write("\t\t\t\t\t<form name=\"alampage\" method=\"post\" id=\"mypage\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p class=\"forgot\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"logincom.jsp\" id=\"mypage\">내가 쓴 게시물</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"forgot\">\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"bookingclub\" href=\"\">즐겨찾는구장 </a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"forgot\">\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"board\" href=\"\">환불계좌등록 </a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"navmid\">\r\n");
      out.write("\t\t\t<div id=\"navmid_1\" class=\"slideDown\">\r\n");
      out.write("\t\t\t\t<a href=\"match_apply.jsp\">팀매치신청</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"navmid_2\" class=\"slideDown\">\r\n");
      out.write("\t\t\t\t<a href=\"yonglist_1.jsp\">용병등록</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"navmid_3\" class=\"slideDown\">\r\n");
      out.write("\t\t\t\t<a href=\"teamlist.do?command=teamlist\">팀원모집</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
