/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-01 13:48:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.TeamBoardListDto;
import vo.GalBoardDto;
import vo.PageInfo;
import java.util.*;
import java.text.SimpleDateFormat;

public final class team_005fboard_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.TeamBoardListDto");
    _jspx_imports_classes.add("vo.GalBoardDto");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("vo.PageInfo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<TeamBoardListDto> teamboardlist = (ArrayList<TeamBoardListDto>) request.getAttribute("teamboardlist");
	PageInfo pageInfo = (PageInfo) request.getAttribute("pageInfo");
	int listCount = pageInfo.getListCount();
	int nowPage = pageInfo.getPage();
	int maxPage = pageInfo.getMaxPage();
	int startPage = pageInfo.getStartPage();
	int endPage = pageInfo.getEndPage();

      out.write("\r\n");
      out.write("\r\n");

	//2020_01_02 수정부분
	String url = request.getServletPath();
	session.setAttribute("url", url);
	String includeurl = "header.jsp";
	String uss = (String) session.getAttribute("id");
	String log = "로그인";
	if (uss == null)
		uss = "GUEST";
	else {
		log = "로그아웃";
		includeurl = "sign_login.jsp";
	}
	//수정부분 끝

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"Generator\" content=\"EditPlus®\">\r\n");
      out.write("<meta name=\"Author\" content=\"\">\r\n");
      out.write("<meta name=\"Keywords\" content=\"\">\r\n");
      out.write("<meta name=\"Description\" content=\"\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>팀게시판</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/galboardstyle.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Black+Han+Sans&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/signbutton.css\">\r\n");
      out.write("<!--기본적인 body등의 css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/basicStyle.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/navmid33.css\">\r\n");
      out.write("<!--Q&A에 펠요한 css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Q&Astyle.css\" media=\"screen\">\r\n");
      out.write("<!-- Q&A에 필요한 script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"Q&Ascript.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--주메뉴밑줄기능-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/borderRightLeft.css\" media=\"screen\">\r\n");
      out.write("<!-- 광호Q&A -->\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<!--2020.01.03 추가 css 분리-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/logform.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/galstyle.css\" media=\"screen\">\r\n");
      out.write("<!--2020.01.03 추가 javascript.가입기능 분리-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/signjs.js\"></script>\r\n");
      out.write("<!--서브메뉴부르는css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style2.css\" media=\"screen\">\r\n");
      out.write("<!--배너2 자동슬라이드-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.infinitecarousel.js\"></script>\r\n");
      out.write("<!--footer css 파일 추가-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("\r\n");
      out.write("<!----------------------------서브메뉴마우스오버기능-------------------------->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/subMenuMouseOver.css\">\r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일(따로 빼면 에러)-------------------------->\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#forgot_username_link').tipsy({\r\n");
      out.write("\t\t\tgravity : 'w'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"css/front.css\" media=\"screen, projection\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"js/jquery2.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\".signin\").click(function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t$(\"fieldset#signin_menu\").toggle();\r\n");
      out.write("\t\t\t$(\".signin\").toggleClass(\"menu-open\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"fieldset#signin_menu\").mouseup(function() {\r\n");
      out.write("\t\t\treturn false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).mouseup(function(e) {\r\n");
      out.write("\t\t\tif ($(e.target).parent(\"a.signin\").length == 0) {\r\n");
      out.write("\t\t\t\t$(\".signin\").removeClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t$(\"fieldset#signin_menu\").hide();\r\n");
      out.write("\t\t\t\t//console.log($(e.target).parent(\"a.mypage\").length);\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!----------------------------alam form 추가 2020.01.06-------------------------->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\".mypage\").click(function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t$(\"fieldset#mypage_menu\").toggle();\r\n");
      out.write("\t\t\t$(\".mypage\").toggleClass(\"menu-open\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"fieldset#mypage_menu\").mouseup(function() {\r\n");
      out.write("\t\t\treturn false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).mouseup(function(e) {\r\n");
      out.write("\t\t\tif ($(e.target).parent(\"a.mypage\").length == 0) {\r\n");
      out.write("\t\t\t\t$(\".mypage\").removeClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t$(\"fieldset#mypage_menu\").hide();\r\n");
      out.write("\t\t\t\tconsole.log($(e.target).parent(\"a.signin\").length);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일여기까지------------------------------------>\r\n");
      out.write("<script>\r\n");
      out.write("\t/*스크롤 내리면 메뉴 위치 이동하는 기능------따로빼면 작동xxxxxx*/\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar shrinkHeader = 30;\r\n");
      out.write("\t\tvar shrinkhollow = 465;\r\n");
      out.write("\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\tvar scroll = getCurrentScroll();\r\n");
      out.write("\t\t\tif (scroll >= shrinkHeader) {\r\n");
      out.write("\t\t\t\t$('#navtop').addClass('shrink');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#navtop').removeClass('shrink');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (scroll >= shrinkhollow) {\r\n");
      out.write("\t\t\t\t$('#navtop').addClass('shrinkhollow');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#navtop').removeClass('shrinkhollow');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction getCurrentScroll() {\r\n");
      out.write("\t\t\treturn window.pageYOffset || document.documentElement.scrollTop;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".subli ul {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tborder: 1px;\r\n");
      out.write("}\r\n");
      out.write("#galtablenav{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("    float: left;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".tab_wrap {\r\n");
      out.write("    border: 1px solid #4b4b4b;\r\n");
      out.write("    height: 72px;\r\n");
      out.write("}\r\n");
      out.write(".t03 {\r\n");
      out.write("    margin: 0px;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("}\r\n");
      out.write(".t03 ul {\r\n");
      out.write("    list-style-type: disc;\r\n");
      out.write("}\r\n");
      out.write(".tab_wrap ul li.on {\r\n");
      out.write("    z-index: 10;\r\n");
      out.write("}\r\n");
      out.write(".tab_wrap ul.t03 li {\r\n");
      out.write("    width: 50%;\r\n");
      out.write("}\r\n");
      out.write(".tab_wrap ul li {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write(".t03 li {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("}\r\n");
      out.write(".t03 li {\r\n");
      out.write("    display: list-item;\r\n");
      out.write("    text-align: -webkit-match-parent;\r\n");
      out.write("}\r\n");
      out.write(".tab_wrap ul li:first-child > a {\r\n");
      out.write("    border-left: 0;\r\n");
      out.write("}\r\n");
      out.write(".tab_wrap ul li.on > a {\r\n");
      out.write("    background: #2c3c57;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".tab_wrap ul li > a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    border-left: 1px solid #2c3c57;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    color: #2c3c57;\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    line-height: 70px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".tab_wrap ul li.on > a:after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    bottom: -13px;\r\n");
      out.write("    margin-left: -6px;\r\n");
      out.write("    width: 13px;\r\n");
      out.write("    height: 13px;\r\n");
      out.write("    background: url(img/bg_tab_arr.png) no-repeat 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--여기부터 팀게시판 css-->\r\n");
      out.write(".league_cont .teams_table {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin-top: 60px;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .search {\r\n");
      out.write("    padding: 14px 0 14px 75px;\r\n");
      out.write("    background: #2c3c57 url(img/icon_league_search.png) no-repeat 0 center;\r\n");
      out.write("    font-size: 0;\r\n");
      out.write("    line-height: 47px;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .search .select:first-child {\r\n");
      out.write("    margin-left: 14px;\r\n");
      out.write("    width: 20%;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .search .select {\r\n");
      out.write("    margin-right: 8px;\r\n");
      out.write("    width: 36%;\r\n");
      out.write("    height: 47px;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .select {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    border: 1px solid #e0e0e0;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .select:after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 12px;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    margin-top: -4px;\r\n");
      out.write("    width: 13px;\r\n");
      out.write("    height: 8px;\r\n");
      out.write("    background: url(img/select_arrow.png) no-repeat center center;\r\n");
      out.write("    background-size: 11px auto;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .search .select label {\r\n");
      out.write("    line-height: 45px;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .select label {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0px;\r\n");
      out.write("    right: 20px;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 10px;\r\n");
      out.write("    color: #404040;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 38px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write(".league_cont label {\r\n");
      out.write("    cursor: default;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .select select {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    padding: 0 4px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 38px;\r\n");
      out.write("    line-height: 38px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("    filter: alpha(opacity=0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".league_cont select {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    border: 1px solid #999;\r\n");
      out.write("    line-height: 22px;\r\n");
      out.write("    height: 22px;\r\n");
      out.write("    color: #a6a6a6;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".league_cont select {\r\n");
      out.write("    -webkit-writing-mode: horizontal-tb !important;\r\n");
      out.write("    text-rendering: auto;\r\n");
      out.write("    color: -internal-light-dark-color(black, white);\r\n");
      out.write("    letter-spacing: normal;\r\n");
      out.write("    word-spacing: normal;\r\n");
      out.write("    text-transform: none;\r\n");
      out.write("    text-indent: 0px;\r\n");
      out.write("    text-shadow: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    text-align: start;\r\n");
      out.write("    -webkit-appearance: menulist;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    white-space: pre;\r\n");
      out.write("    -webkit-rtl-ordering: logical;\r\n");
      out.write("    background-color: -internal-light-dark-color(white, black);\r\n");
      out.write("    cursor: default;\r\n");
      out.write("    margin: 0em;\r\n");
      out.write("    font: 400 13.3333px Arial;\r\n");
      out.write("    border-radius: 0px;\r\n");
      out.write("    border-width: 1px;\r\n");
      out.write("    border-style: solid;\r\n");
      out.write("    border-color: rgb(169, 169, 169);\r\n");
      out.write("    border-image: initial;\r\n");
      out.write("}\r\n");
      out.write(".league_cont option {\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    display: block;\r\n");
      out.write("    white-space: pre;\r\n");
      out.write("    min-height: 1.2em;\r\n");
      out.write("    padding: 0px 2px 1px;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .search_wrap {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 14px;\r\n");
      out.write("    right: 14px;\r\n");
      out.write("    padding-right: 119px;\r\n");
      out.write("}\r\n");
      out.write(".league_cont div {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .search_wrap input {\r\n");
      out.write("    height: 48px;\r\n");
      out.write("}\r\n");
      out.write(".teams_table input[placeholder] {\r\n");
      out.write("    line-height: 1em !important;\r\n");
      out.write("}\r\n");
      out.write(".teams_table input[type='text'], input[type='password'] {\r\n");
      out.write("    -webkit-border-radius: 0;\r\n");
      out.write("    -webkit-appearance: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write(".teams_table input[type='text'], input[type='password'] {\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 3px 9px 3px 9px;\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    color: #383838;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 43px;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write(".teams_table input {\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".teams_table input {\r\n");
      out.write("    -webkit-writing-mode: horizontal-tb !important;\r\n");
      out.write("    text-rendering: auto;\r\n");
      out.write("    color: -internal-light-dark-color(black, white);\r\n");
      out.write("    letter-spacing: normal;\r\n");
      out.write("    word-spacing: normal;\r\n");
      out.write("    text-transform: none;\r\n");
      out.write("    text-indent: 0px;\r\n");
      out.write("    text-shadow: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    text-align: start;\r\n");
      out.write("    -webkit-appearance: textfield;\r\n");
      out.write("    background-color: -internal-light-dark-color(white, black);\r\n");
      out.write("    -webkit-rtl-ordering: logical;\r\n");
      out.write("    cursor: text;\r\n");
      out.write("    margin: 0em;\r\n");
      out.write("    font: 400 13.3333px Arial;\r\n");
      out.write("    padding: 1px 0px;\r\n");
      out.write("    border-width: 2px;\r\n");
      out.write("    border-style: inset;\r\n");
      out.write("    border-color: initial;\r\n");
      out.write("    border-image: initial;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .search_wrap button {\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    width: 120px;\r\n");
      out.write("    height: 48px;\r\n");
      out.write("    background: #4c89cd;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".league_cont button {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    font-family: 'Nanum Gothic','맑은 고딕','AppleGothic','돋움','Dotum', sans-serif;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    -webkit-transition: all 0.25s ease-out;\r\n");
      out.write("    -moz-transition: all 0.25s ease-out;\r\n");
      out.write("    -ms-transition: all 0.25s ease-out;\r\n");
      out.write("    -o-transition: all 0.25s ease-out;\r\n");
      out.write("    transition: all 0.25s ease-out;\r\n");
      out.write("}\r\n");
      out.write(".league_cont button {\r\n");
      out.write("    -webkit-appearance: button;\r\n");
      out.write("    -webkit-writing-mode: horizontal-tb !important;\r\n");
      out.write("    text-rendering: auto;\r\n");
      out.write("    color: buttontext;\r\n");
      out.write("    letter-spacing: normal;\r\n");
      out.write("    word-spacing: normal;\r\n");
      out.write("    text-transform: none;\r\n");
      out.write("    text-indent: 0px;\r\n");
      out.write("    text-shadow: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    align-items: flex-start;\r\n");
      out.write("    cursor: default;\r\n");
      out.write("    background-color: buttonface;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    margin: 0em;\r\n");
      out.write("    font: 400 13.3333px Arial;\r\n");
      out.write("    padding: 1px 6px;\r\n");
      out.write("    \r\n");
      out.write("    border-style: outset;\r\n");
      out.write("    border-color: buttonface;\r\n");
      out.write("    border-image: initial;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .league_cont .teams_table .search_wrap button span {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding-right: 30px;\r\n");
      out.write("    background: url(/images/content/icon_league_search_s.png) no-repeat right center;\r\n");
      out.write("    background-size: auto 40px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("body .league_cont{\r\n");
      out.write("    *overflow-y: ;\r\n");
      out.write("    width: 983px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    min-width: 320px;\r\n");
      out.write("    color: #403d3f;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-family: 'Nanum Gothic','NanumBarunGothic','AppleGothic','Dotum', sans-serif;\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    line-height: 26px;\r\n");
      out.write("    -webkit-text-size-adjust: none;\r\n");
      out.write("    word-spacing: 0;\r\n");
      out.write("    letter-spacing: -0.3px;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .table_wrap table {\r\n");
      out.write("    border: 0;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .table_wrap table {\r\n");
      out.write("    border: 1px solid #636363;\r\n");
      out.write("    border-top: 0;\r\n");
      out.write("    border-left: 0;\r\n");
      out.write("}\r\n");
      out.write(".league_cont table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border: 0 none;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    border-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write(".league_cont table {\r\n");
      out.write("    display: table;\r\n");
      out.write("    \r\n");
      out.write("    border-spacing: 2px;\r\n");
      out.write("    border-color: grey;\r\n");
      out.write("}\r\n");
      out.write(".league_cont table caption {\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 0;\r\n");
      out.write("    line-height: 0px;\r\n");
      out.write("    visibility: hidden;\r\n");
      out.write("}\r\n");
      out.write(".league_cont caption {\r\n");
      out.write("    display: table-caption;\r\n");
      out.write("    text-align: -webkit-center;\r\n");
      out.write("}\r\n");
      out.write(".league_cont colgroup {\r\n");
      out.write("    display: table-column-group;\r\n");
      out.write("}\r\n");
      out.write(".league_cont thead {\r\n");
      out.write("    display: table-header-group;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    border-color: inherit;\r\n");
      out.write("}\r\n");
      out.write(".league_cont tr {\r\n");
      out.write("    display: table-row;\r\n");
      out.write("    vertical-align: inherit;\r\n");
      out.write("    border-color: inherit;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .table_wrap table thead tr th {\r\n");
      out.write("    border: 0;\r\n");
      out.write("    border-top: 2px solid #2c3c57;\r\n");
      out.write("    border-bottom: 2px solid #2c3c57;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    color: #4d4d4d;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .table_wrap table thead tr th {\r\n");
      out.write("    padding: 21px 0;\r\n");
      out.write("    height: 22px;\r\n");
      out.write("    background: #f0f1f3;\r\n");
      out.write("    color: #383838;\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("    line-height: 22px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap table th, .table_wrap table td {\r\n");
      out.write("    border-top: 1px solid #636363;\r\n");
      out.write("    border-left: 1px solid #636363;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write(".league_cont table th, table td {\r\n");
      out.write("    border: 0 none;\r\n");
      out.write("}\r\n");
      out.write(".league_cont table th {\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write(".league_cont th {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    vertical-align: inherit;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    text-align: -internal-center;\r\n");
      out.write("}\r\n");
      out.write(".league_cont tbody {\r\n");
      out.write("    display: table-row-group;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    border-color: inherit;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .table_wrap table tbody tr:nth-child(2n-1) td {\r\n");
      out.write("    background: #f0f1f3;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .table_wrap table tbody tr td:first-child {\r\n");
      out.write("    border-left: 0;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .table_wrap table tbody tr td {\r\n");
      out.write("    padding: 10px 0;\r\n");
      out.write("    border-top: 0;\r\n");
      out.write("    border-bottom: 1px solid #d5d8dd;\r\n");
      out.write("    border-left: 1px solid #d5d8dd;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    line-height: 50px;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap table tbody tr td {\r\n");
      out.write("    padding: 18px 0;\r\n");
      out.write("    height: 20px;\r\n");
      out.write("    color: #2a2a2a;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    line-height: 28px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    word-break: keep-all;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap table th, .table_wrap table td {\r\n");
      out.write("    border-top: 1px solid #636363;\r\n");
      out.write("    border-left: 1px solid #636363;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write(".league_cont table th, table td {\r\n");
      out.write("    border: 0 none;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .table_wrap table tbody tr td .emb_wrap {\r\n");
      out.write("    margin: 0 22px;\r\n");
      out.write("    padding-left: 75px;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    line-height: 50px;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap table tbody tr td .emb_wrap {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    padding-left: 55px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 32px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .table_wrap table tbody tr td .btn_view {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 0 19px 0 19px;\r\n");
      out.write("    height: 42px;\r\n");
      out.write("    background: #4c89cd;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    line-height: 42px;\r\n");
      out.write("}\r\n");
      out.write(".league_cont a:visited {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".league_cont a {\r\n");
      out.write("    color: #000;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".league_cont a .team{\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("}\r\n");
      out.write(".league_cont a:-webkit-any-link {\r\n");
      out.write("    color: -webkit-link;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .h_tit {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin-bottom: 45px;\r\n");
      out.write("    padding-bottom: 24px;\r\n");
      out.write("    font-size: 60px;\r\n");
      out.write("    font-family: 'NanumBarunGothicL';\r\n");
      out.write("    line-height: 60px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .h_tit:after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    margin-left: -49px;\r\n");
      out.write("    width: 98px;\r\n");
      out.write("    height: 2px;\r\n");
      out.write("    background: #bfc4cc;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap table tbody tr td .emb_wrap .emb img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .table_wrap table tbody tr td .emb_wrap .emb {\r\n");
      out.write("    width: 50px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("}\r\n");
      out.write(".table_wrap table tbody tr td .emb_wrap .emb {\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 32px;\r\n");
      out.write("    height: 32px;\r\n");
      out.write("}\r\n");
      out.write(".league_cont .teams_table .search_wrap button span {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding-right: 30px;\r\n");
      out.write("    background: url(img/icon_league_search_s.png) no-repeat right center;\r\n");
      out.write("    background-size: auto 40px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin-top: 42px;\r\n");
      out.write("    font-size: 0;\r\n");
      out.write("    line-height: 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    letter-spacing: -10px;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap a.btn_page.prev {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    background: #fff url(img/icn_page_prev.png) no-repeat center center;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap a.btn_page {\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap a {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-left: 8px;\r\n");
      out.write("    width: 79px;\r\n");
      out.write("    height: 41px;\r\n");
      out.write("    border: 1px solid #cecece;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    color: #afafaf;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 41px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    letter-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write(".hide {\r\n");
      out.write("    display: block;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 0;\r\n");
      out.write("    text-indent: -9999px;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .page {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin: 0 22px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .page a.on {\r\n");
      out.write("    border: 1px solid #2c3c57;\r\n");
      out.write("    background: #2c3c57;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .page a:first-child {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap .page a {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 41px;\r\n");
      out.write("    height: 41px;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap a {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-left: 8px;\r\n");
      out.write("    width: 79px;\r\n");
      out.write("    height: 41px;\r\n");
      out.write("    border: 1px solid #cecece;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    color: #afafaf !important;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 41px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    letter-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap a.btn_page.next {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    background: #fff url(img/icn_page_next.png) no-repeat center center;\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap a.btn_page {\r\n");
      out.write("}\r\n");
      out.write(".pager_wrap a {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-left: 8px;\r\n");
      out.write("    width: 79px;\r\n");
      out.write("    height: 41px;\r\n");
      out.write("    border: 1px solid #cecece;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    color: #afafaf;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 41px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    letter-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write("<!--여기까지 팀게시판css-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, includeurl, out, false);
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div id=\"mainleft\">\r\n");
      out.write("\t\t<div id=\"leftbanner\">\r\n");
      out.write("\t\t\t<div id=\"banner1\">\r\n");
      out.write("\t\t\t\t<img src=\"img/20191211.jpg\" width=\"100%\" height=\"100%\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"banner3\">\r\n");
      out.write("\t\t\t\t<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25325.265446899888!2d127.02924799651784!3d37.492391917303266!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357ca5bed583f92d%3A0xc93c837d2875ade6!2z7ZKL7IK07J6l!5e0!3m2!1sko!2skr!4v1575961834128!5m2!1sko!2skr\" width=\"100%\" height=\"100%\" frameborder=\"0\" style=\"border: 0;\" allowfullscreen=\"\"> </iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\t\t<section id=\"mainright\">\r\n");
      out.write("\t\t\t<div id=\"matList\">\r\n");
      out.write("\t\t\t\t<div class=\"sec_ban2 margin2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"writeboardtitle\">공지사항</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-striped margin2\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr id=\"tabletitle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thtitle\" style=\"text-align: center\"><span>제목</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thname\"><span>작성자</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thdate\"><span>작성일</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thview\"><span>조회</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thgongji\">공지</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thtitle\"><a href>필 독 !! 그린컴퓨터 풋살팀 공지사항</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thname\">김 팡 호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thdate\">2019. 12. 10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thview\">30,589</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thgongji\">공지</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thtitle\"><a href> 사진 깨짐 현상이 일어나는 이유 !</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thname\">김 팡 호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thdate\">2019. 12. 08</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thview\">89,152</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thgongji\">공지</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thtitle\"><a href> 자유롭게 팀의 사진을 올리시면 됩니다 !</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thname\">김 팡 호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thdate\">2019. 12. 05</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thview\">60,895</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"galtablenav\">\r\n");
      out.write("\t\t\t\t\t<div class=\"tab_wrap\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"t03\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"galList.bo\">팀 갤러리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"on\"><a href=\"teamboardlist.do?command=teamboardlist\">팀 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"writeboardtitle\" style=\"margin-top: 50px;\">Green Computer 팀 게시판</div>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"글쓰기\" class=\"signbutton signbutton5 buttonmargin\" onClick=\"script: location.href='teamboardlistwrite.do?command=team_board_list_writeform'\" style=\"margin-right: 34px;\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"container\" style=\"width: 1193px;\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"league_cont team\">\r\n");
      out.write("\t\t\t\t\t<div class=\"teams_table\" style=\"clear:both;width: 950px;\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t\t\t\t<form name=\"frm_search\" method=\"get\" action=\"?\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"select\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"select01\" style=\"width:100%;\">전체</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"select01\" name=\"grade\" class=\"select_box\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">성인부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">초등부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"select\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"select02\" style=\"width:100%;\">전국현황</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"select02\" name=\"bcode\" class=\"select_box\" style=\"width:100%;\" onchange=\"fn_SelBranch();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">전국현황</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0033\">가천대학교 운동장</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0005\">대전 탄방점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0001\">동대문점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0006\">동대전점 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0007\">부산 가야점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0031\">부산 북구점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0003\">서수원점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0002\">안산 고잔점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0008\">울산 남구점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0024\">울산 북구점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0004\">일산점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0010\">전주 완산점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0009\">창원점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0028\">GLOBAL ARENA (Japan)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"HM0032\">Seogwipo, JEJU</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"search_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"search\" value=\"\" placeholder=\"팀명을 입력 하세요\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"search_button\" onclick=\"this.form.submit();\"><span>검색</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"id\" id=\"id\" value=\"");
      out.print(uss);
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<caption>팀 테이블</caption>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col style=\"width:80px\" class=\"tb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<col style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col style=\"width:130px\" class=\"w07\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col style=\"width:130px\" class=\"tb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col style=\"width:100px\" class=\"w07\">\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"tb\">글번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">글제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">글쓴이</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"tb\">게시일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">조회수</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
int count = 0;
									if(teamboardlist != null){
										for(int i=0; i<teamboardlist.size(); i++){
											
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"tb\">");
      out.print(teamboardlist.get(i).getT_B_NO());
      out.write("</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"emb_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"teamboarddetail.do?command=teamboarddetail&teamBoardNo=");
      out.print(teamboardlist.get(i).getT_B_NO());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"team\">");
      out.print(teamboardlist.get(i).getT_B_SUBJECT());
      out.write("</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(teamboardlist.get(i).getId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"tb\">");
      out.print(teamboardlist.get(i).getT_B_DATE());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(teamboardlist.get(i).getT_B_READCOUNT() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
	count=0;	
								}
									}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Page -->\r\n");
      out.write("\t\t\t\t\t\t<section id=\"pageList\" style=\"clear:both; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t");

							if (nowPage <= 1) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a style=\"color:black;\">이전</a></li>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"teamboardlist.do?command=teamboardlist&page=");
      out.print(nowPage - 1);
      out.write("\">이전</a></li>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							for (int a = startPage; a <= endPage; a++) {
									if (a == nowPage) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a style=\"color:black;\">");
      out.print(a);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"teamboardlist.do?command=teamboardlist&page=");
      out.print(a);
      out.write('"');
      out.write('>');
      out.print(a);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a></li>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							if (nowPage >= maxPage) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a style=\"color:black;\">다음</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"teamboardlist.do?command=teamboardlist&page=");
      out.print(nowPage + 1);
      out.write("\">다음</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t<!-- //Page -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<aside style=\"margin-left: -25px;position: relative;top: -282px;\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-head\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"form\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"subli logolistmargin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><img src=\"img/liverpool.jpg\" align=\"absmiddle\" class=\"subli_img\" /> <a href=\"#/Liverpool/\">Green Computer</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><img src=\"img/mu.png\" align=\"absmiddle\" class=\"subli_img\" /> <a href=\"#/Manchester United/\">Blue Computer</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><img src=\"img/mcity.png\" align=\"absmiddle\" class=\"subli_img\" /> <a href=\"#/Manchester City/\">Red Computer</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><img src=\"img/chelsea.png\" align=\"absmiddle\" class=\"subli_img\" /> <a href=\"#/Chelsea/\">White Computer</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><img src=\"img/tottenham.png\" align=\"absmiddle\" class=\"subli_img\" /> <a href=\"#/Chelsea/\">Yellow Computer</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><img src=\"img/arsenal.png\" align=\"absmiddle\" class=\"subli_img\" /> <a href=\"#/Arsenal/\">Super Computer</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><img src=\"img/liverpool.jpg\" align=\"absmiddle\" class=\"subli_img\" /> <a href=\"#/Arsenal/\">Super Computer</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><img src=\"img/mcity.png\" align=\"absmiddle\" class=\"subli_img\" /> <a href=\"#/Arsenal/\">Super Computer</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><img src=\"img/tottenham.png\" align=\"absmiddle\" class=\"subli_img\" /> <a href=\"#/Arsenal/\">Super Computer</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</aside>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<footer id=\"footer\" style=\"margin-top:200px;\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "quickbar.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
