/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-01 13:39:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.YonglistDao;
import java.util.ArrayList;
import vo.YonglistDto;
import java.util.Date;

public final class yonglist_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.YonglistDao");
    _jspx_imports_classes.add("vo.YonglistDto");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String url = request.getServletPath();
	session.setAttribute("url", url);
	//2020_01_02 수정부분
	String includeurl = "header.jsp";
	String uss = (String) session.getAttribute("id");
	String log = "로그인";
	if (uss == null)
		uss = "GUEST";
	else {
		log = "로그아웃";
		includeurl = "sign_login.jsp";
	}
	//수정부분 끝
	//2020.01.14 로그인 id 수정
	String yid = (String) session.getAttribute("id");

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"Generator\" content=\"EditPlus®\">\r\n");
      out.write("<meta name=\"Author\" content=\"\">\r\n");
      out.write("<meta name=\"Keywords\" content=\"\">\r\n");
      out.write("<meta name=\"Description\" content=\"\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>yonglist</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/boardpop.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/borderRightLeft.css\" media=\"screen\">\r\n");
      out.write("<!-- 광호Q&A -->\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<!--용병리스트 게시판 css파일 수정 2020.01.08-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"yonglist_1_body.css\">\r\n");
      out.write("<!----------------------------바디 스타일------------------------------------>\r\n");
      out.write("\r\n");
      out.write("<!--기본적인 body등의 css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/basicStyle.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/navmid33.css\">\r\n");
      out.write("\r\n");
      out.write("<!--서브메뉴부르는css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style2.css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<!--배너2 자동슬라이드-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.infinitecarousel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!----------------------------서브메뉴마우스오버기능-------------------------->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/subMenuMouseOver.css\">\r\n");
      out.write("<!-- 20200116 용병 버튼 크기 조절 by 문경이형 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/signbutton.css\">\r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일(따로 빼면 에러)-------------------------->\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#forgot_username_link').tipsy({\r\n");
      out.write("\t\t\tgravity : 'w'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"css/front.css\" media=\"screen, projection\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"js/jquery2.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".signin\").click(function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t$(\"fieldset#signin_menu\").toggle();\r\n");
      out.write("\t\t\t$(\".signin\").toggleClass(\"menu-open\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"fieldset#signin_menu\").mouseup(function() {\r\n");
      out.write("\t\t\treturn false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).mouseup(function(e) {\r\n");
      out.write("\t\t\tif ($(e.target).parent(\"a.signin\").length == 0) {\r\n");
      out.write("\t\t\t\t$(\".signin\").removeClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t$(\"fieldset#signin_menu\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일여기까지------------------------------------>\r\n");
      out.write("<script>\r\n");
      out.write("\t/*스크롤 내리면 메뉴 위치 이동하는 기능------따로빼면 작동xxxxxx*/\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar shrinkHeader = 30;\r\n");
      out.write("\t\tvar shrinkhollow = 465;\r\n");
      out.write("\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\tvar scroll = getCurrentScroll();\r\n");
      out.write("\t\t\tif (scroll >= shrinkHeader) {\r\n");
      out.write("\t\t\t\t$('#navtop').addClass('shrink');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#navtop').removeClass('shrink');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (scroll >= shrinkhollow) {\r\n");
      out.write("\t\t\t\t$('#navtop').addClass('shrinkhollow');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#navtop').removeClass('shrinkhollow');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction getCurrentScroll() {\r\n");
      out.write("\t\t\treturn window.pageYOffset || document.documentElement.scrollTop;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!--2020.01.09Overray css추가 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/qnaOverray.css\">\r\n");
      out.write("<!----------------------------오버레이 화면 띄우는 스크립트------------------------------------>\r\n");
      out.write("<script>\t\t\t\t\t\t\r\n");
      out.write("\tfunction selectOne(index,yid) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\t\r\n");
      out.write("\t\turl:\"./yongSelectOne.jsp\",       \r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tindex:index,\r\n");
      out.write("\t\t\tyid:yid\r\n");
      out.write("\t\t},\t\r\n");
      out.write("\t\tsuccess:whenSuccess2,\r\n");
      out.write("\t\terror:whenError2\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\tfunction whenSuccess2(resdata){\r\n");
      out.write("\t\t\tconsole.log(resdata);\r\n");
      out.write("\t\t\t$(\"#innerpop\").html(resdata);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction whenError2(){\r\n");
      out.write("\t\t\talert(\"리스트에러\");\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".pagination li a {\r\n");
      out.write("\tposition: unset;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signbutton6:hover {\r\n");
      out.write("\tcolor: #e0e0e0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signbutton6 {\r\n");
      out.write("\tbackground-color: #555555;\r\n");
      out.write("\tfont-size: 19px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- 한글글씨체적용 /아이디찾기 제목-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/galboardstyle.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Black+Han+Sans&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 유즈빈 사용 -->\r\n");
      out.write("\t");
      dao.YonglistDao yl = null;
      yl = (dao.YonglistDao) _jspx_page_context.getAttribute("yl", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (yl == null){
        yl = new dao.YonglistDao();
        _jspx_page_context.setAttribute("yl", yl, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, includeurl, out, false);
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div id=\"mainleft\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"leftbanner\">\r\n");
      out.write("\t\t\t<div id=\"banner1\">\r\n");
      out.write("\t\t\t\t<img src=\"img/20191211.jpg\" width=\"100%\" height=\"100%\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"banner3\">\r\n");
      out.write("\t\t\t\t<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25325.265446899888!2d127.02924799651784!3d37.492391917303266!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357ca5bed583f92d%3A0xc93c837d2875ade6!2z7ZKL7IK07J6l!5e0!3m2!1sko!2skr!4v1575961834128!5m2!1sko!2skr\" width=\"100%\" height=\"100%\" frameborder=\"0\" style=\"border: 0;\" allowfullscreen=\"\"></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\t\t<section id=\"mainright\">\r\n");
      out.write("\t\t\t<div id=\"matList\">\r\n");
      out.write("\t\t\t\t<div class=\"writeboardtitle\" style=\"margin-top: 5px; font-size: 50px; line-height: 80px; text-align: center;\">용 병 등 록</div>\r\n");
      out.write("\t\t\t\t<div class=\"cbox\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-striped\" style=\"font-size: 16px;\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr id=\"tabletitle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thno\"><span>지점</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thtitle\" style=\"text-align: center;\"><span>매치일자</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thtitle\" style=\"text-align: center;\"><span>매치시간대</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thname\"><span>작성자</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"thview\"><span>신청</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"signbutton signbutton6\" type=\"button\" value=\"용병등록\" style=\"float: right; margin: 10px;\" onClick=\"location.href='yongsign.jsp'\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								ArrayList<YonglistDto> yong = yl.select();
								for (int i = 0; i < yong.size(); i++) {
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thgongji\">");
      out.print(yong.get(i).getY_b_branch());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thdate2\" style=\"text-align: center;\"><a onClick=\"selectOne(");
      out.print(yong.get(i).getYno());
      out.write(',');
      out.write('\'');
      out.print(yong.get(i).getYid());
      out.write("'); \" class=\"button\" id=\"listtt\"> ");
      out.print(yong.get(i).getY_b_schedule());
      out.write("</a></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thdate2\" style=\"text-align: center;\">");
      out.print(yong.get(i).getY_b_time());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thname\">");
      out.print(yong.get(i).getY_b_name());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"thview\">");
      out.print(yong.get(i).getY_b_status());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<div id=\"innerpop\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">6</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">7</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">8</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">9</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">10</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">다음 ></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<select class=\"form-control\" style=\"width: 200px; float: left; margin-left: 150px;\">\r\n");
      out.write("\t\t\t\t\t\t<option>전체기간\r\n");
      out.write("\t\t\t\t\t</select> <select class=\"form-control\" style=\"width: 200px; float: left; margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<option>제목+내용\r\n");
      out.write("\t\t\t\t\t</select> <input type=\"text\" class=\"form-control\" id=\"exampleInputEmail1\" placeholder=\"검색어를 입력하세요\" class=\"form-control\" style=\"width: 300px; float: left; margin-left: 10px;\"> <input class=\"btn btn-default\" type=\"button\" value=\"검 색\" style=\"float: left; margin-left: 10px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
